### PR TITLE
LPS-79618 language key

### PR DESCRIPTION
**Pull request by linolaoj**
Please run buildLang.
Thanks!
cc:@marcelabc

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/linolaoj/liferay-portal/pull/128. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/a891853d3444~2...a891853d3444) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
