### PR TITLE
LPS-87795 Return global workflow definition link count

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65314. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/af884c3bd109~1...af884c3bd109) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
