### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test

**Comment by vicnate5** [comment]
@pedroqueiroz Will cover with poshi (https://issues.liferay.com/browse/LRQA-39548)

**Comment by pedroqueiroz** [comment]
Thanks, @vicnate5 ! Also, are the test failures related to this PR?

**Comment by pedroqueiroz** [comment]
LGTM!

**Comment by vicnate5** [comment]
@pedroqueiroz Test failures not related to this pull.

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56466. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/eba6064a0cd6~3...eba6064a0cd6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
