### PR TITLE
Revert "LPS-197353 Making tests context independent"

This reverts commit fa45c4418a6ed3ad9d00a3da8b5891e4ea0f06b8.

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:workflow

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@catarineaguiar can you watch this PR?

See previous regression at https://github.com/rafaprax/liferay-portal/pull/1330#issuecomment-1793112920

**Comment by catarineaguiar** [comment]
ci:test:workflow

**Comment by catarineaguiar** [comment]
running workflow suite on https://github.com/catarineaguiar/liferay-portal/pull/129

**Comment by rafaprax** [comment]
ci:test:workflow

**Comment by catarineaguiar** [comment]
@rafaprax regression found:

```
[beanshell]      [exec] com.liferay.portal.workflow.kaleo.upgrade.v1_4_1.test.UpgradeKaleoDefinitionVersionTest > testCreateKaleoDefinitionVersion FAILED
[beanshell]      [exec]     com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.workflow.WorkflowException: Unable to convert JSON to XML
[beanshell]      [exec]     	at com.liferay.portal.kernel.service.persistence.impl.BasePersistenceImpl.processException(BasePersistenceImpl.java:640)
[beanshell]      [exec]     	at com.liferay.portal.workflow.kaleo.service.persistence.impl.KaleoDefinitionPersistenceImpl.fetchByC_N(KaleoDefinitionPersistenceImpl.java:780)
[beanshell]      [exec]     	at com.liferay.portal.workflow.kaleo.service.persistence.impl.KaleoDefinitionPersistenceImpl.fetchByC_N(KaleoDefinitionPersistenceImpl.java:661)
[beanshell]      [exec]     	at com.liferay.portal.workflow.kaleo.service.persistence.impl.KaleoDefinitionPersistenceImpl.findByC_N(KaleoDefinitionPersistenceImpl.java:627)
[beanshell]      [exec]     	at com.liferay.portal.workflow.kaleo.service.impl.KaleoDefinitionLocalServiceImpl.getKaleoDefinition(KaleoDefinitionLocalServiceImpl.java:237)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-11/test-1-33/test-portal-acceptance-pullrequest(master)/4636/modules-integration-mysql57-jdk8/0/1/jenkins-console.txt.gz?authuser=0)

[CPKaleoformsadmin#EditUploadedWorkflowViaViewTabViaAddProcess](https://testray.liferay.com/home/-/testray/case_results/2453653564) Passed

**Comment by rafaprax** [comment]
fixed

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
resent here https://github.com/rafaprax/liferay-portal/pull/1333

**Pull request closed without merging**
