### PR TITLE
[TECHNICAL-SUPPORT] LPS-85177

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @brianikim 

Notes from Brian:

> https://issues.liferay.com/browse/LPS-85177
> 
> The issue here is that when SPA is disabled and you try to create a Structure with a field name of "submit", the structure will not be able to be saved.
> 
> The reason for this issue is that when the field is created and you change the field name, the corresponding HTML input tag for the field changes its name to "submit".
> 
> This process causes a conflict because when Liferay tries to carry out the default submit event for the form, the input tag is instead used as the method call rather than the default javascript form.submit().
> 
> My proposed solution is to prevent users from naming the field as lower-case "submit".
> 
> I do not have the translator for the language key; I would greatly appreciate it if you could do the auto-generate portion.
> 
> Please let me know if you have any questions. Thanks.
> 
> Sincerely,
> Brian Kim

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by brianikim** [comment]
Hello @rafaprax ,

Any updates on this PR? Thanks.

Sincerely,
Brian Kim

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63123. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/7aa9aadf1d01~2...7aa9aadf1d01) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63125. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/35e8450647da~3...35e8450647da) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63135. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/63912b7ede96~3...63912b7ede96) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
