### PR TITLE
LPS-80078 | master

### PR DESCRIPTION
**Pull request by vicnate5**
@alinedoleron @pedroqueiroz https://github.com/rafaprax/liferay-portal/pull/599

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/610. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/0e072dacf2d9~1...0e072dacf2d9) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
