### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
@rafaprax , test failures are unrelated. :) cc. @vicnate5

**Comment by rafaprax** [comment]
LGTM

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55930. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/678030e15378~1...678030e15378) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55935. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/2d29bc199efc~2...2d29bc199efc) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
