### PR TITLE
LPS-112909 Assigned to in Notification does not show all users

### PR DESCRIPTION
**Pull request by IstvanD**
Hi @rafaprax 

Could you please review this pull request?

`assignableUsers` is a `TreeSet`, and as a `Set`, it doesn't allow duplicates. As it employs a `UserFirstNameComparator`, it will filter duplicates by the User's full name (as `UserFirstNameComparator` compares not just by the first name but by the full name).
However, Users can share the same full name. If there is more than one User whose full name is both Test Test, only one of them will be returned.

In contrast, the screen name must be unique, so it is more appropriate to apply it's comparator for the `TreeSet`.

I also modified the listing of the Users so that it displays the screen name, and, along with the full name, in parentheses.

Please let me know if this approach is correct, or it should be changed (for example, compare by and display email address instead of screen name).

@inacionery

Thank you and best regards,
István

### CODE REVIEW

**Comment by rafaprax** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:workflow

**Comment by rafaprax** [comment]
Hey @rodrigocunhaa, I've checked and these failures are real. They were caused by @IstvanD fix. So, we need to change the impacted tests to be compatible with the new behavior. Can you please update the broken test cases?

/cc @inacionery

**Comment by rodrigocunhaa** [comment]
Hey @rafaprax, sure, I'll do that.

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
@rafaprax, there you go: https://github.com/rafaprax/liferay-portal/pull/1038

**Comment by rafaprax** [comment]
Thx @rodrigocunhaa

**Pull request closed without merging**
