### PR TITLE
ResourceImpl components refactor concept

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:help

**Comment by rafaprax** [comment]
ci:test:headless

**Comment by rafaprax** [comment]
ci:test:objects

**Comment by rafaprax** [comment]
ci:test:startup

**Comment by rafaprax** [comment]
ci:test:object

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
In the last push I just reorganized the commits, so no need to rerun tests.

CC: @catarineaguiar @rafaprax

**Comment by catarineaguiar** [comment]
@MrJohn1911 semver error:

```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/portal-vulcan/portal-vulcan-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.portal.vulcan.fields                   MAJOR      2.2.0      2.2.0      3.0.0      VERSION INCREASE REQUIRED
     [exec]     	-   interface  com.liferay.portal.vulcan.fields.NestedFieldSupport
     [exec]     		-   access     abstract
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 39.0.0
     [exec]         at org.junit.Assert.fail(Assert.java:88)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-08/test-1-37/test-portal-acceptance-pullrequest(master)/13638/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
In the last push, the class `com.liferay.headless.commerce.admin.catalog.internal.resource.v1_0.ProductOptionValueResourceImpl` was added to the pull.

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Pull request closed without merging**
