### PR TITLE
LPS-79139 Add drag and drop support when user drops a set of fields

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test

**Comment by alinedoleron** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56871. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
