### PR TITLE
LPS-99441 | LPS-104874 Apply process step filter on "view all assignees" link

### PR DESCRIPTION
**Pull request by albinojunior**

### CODE REVIEW

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
resent here https://github.com/rafaprax/liferay-portal/pull/976 with a small SF

**Comment by rafaprax** [comment]
ci:stop

**Pull request closed without merging**
