### PR TITLE
LPS-81468 Check for update permission before previewing form

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/659. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/cb191b4ca942~1...cb191b4ca942) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/59075. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/5d88196c3d7f~1...5d88196c3d7f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
