### PR TITLE
LPS-80303 Apply Clay classes to alert float on the top of screen

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
LGTM!

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57915. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/d1eefa99a3ab~1...d1eefa99a3ab) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
