### PR TITLE
LPS-81678 If Rule tab has class 'disabled'  do nothing

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
Hi @vicnate5, please, could you check if this failure related to the fix?

**Comment by vicnate5** [comment]
@alinedoleron Failure not related. This test has become flaky recently. When a field is repeated, it is given a random string in the "field name". The test sometimes getting the wrong "field name" when trying to read the field name from the UI. This might be difficult to catch.

**Comment by rafaprax** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/59667. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/ddb0b96d25e5~2...ddb0b96d25e5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/inacionery/liferay-portal/pull/697.

**Pull request closed without merging**
