### PR TITLE
LPS-77278 Remove callback from evaluation and migrate it's functions to _configureSideBar. It's not necessary to tie these functions to the evaluation, since the field settings in sidebar are already fetched before the evaluation is called.

### PR DESCRIPTION
**Pull request by pedroqueiroz94**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
ci:test

**Comment by pedroqueiroz94** [comment]
ci:stop

**Comment by rafaprax** [comment]
Hey @clovisdasilvaneto Could you please review it? Thx

**Comment by rafaprax** [comment]
Pull request forwarded to https://github.com/clovisdasilvaneto/liferay-portal/pull/15. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
