### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
Hi @vicnate5 , is `Forms#AddElementSetsWithTranslation` failure related to the fix or is it an isolated issue?

Thanks!

**Comment by vicnate5** [comment]
@pedroqueiroz The failing test shows a regression. The problem does not occur at head, only on this pull.

When you add an Element to a page that has a Required. The asterisk will not immediately display on the form builder.

Steps to Reproduce:
1. Add an Element Set with a Required Text Field
2. Add a new form
3. Drag the created element set to the Form builder
4. View Text field

**Expected** Required Asterisk
**Actual** No Asterisk
screenshot 2018-02-26 10 05 51

**Comment by pedroqueiroz** [comment]
hey @vicnate5 , I noticed this behavior, but I don't know if there is something we can do about it, since this is the new implementation of the required asterisk, according to Clay.

Will further investigate this, thanks!

**Comment by pedroqueiroz** [comment]
I will resend this in another PR. Thanks for the help, @vicnate5 !

**Pull request closed without merging**
