### PR TITLE
LPS-167148 Avoid call the _bundleContext.ungetService(serviceReference) twice. It is causing the deactivation of the JournalArticleIndexer that it is the reason why the JournalArticleIndexer is with state satisfied after a reindex process.

So, it is happening because the JournalArticleIndexer is being modified to be a non-immediate component and the SearchEngineInitializer#_reindex open/close a tracker for every reindex causing the issue.

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:startup

**Comment by rafaprax** [comment]
ci:test:echo

**Comment by catarineaguiar** [comment]
@rafaprax testes com falhas unicas:

[RecycleBinWithWebContent#RestoreWebContentWithArticleVersions](https://testray.liferay.com/home/-/testray/case_results/2059039800?tab=history)

[ContentPageTemplatesExportImport#IgnoreFragmentNotExistInSiteWhenImportContentPageTemplate](https://testray.liferay.com/home/-/testray/case_results/2059044307)

[ContentPagesUI#ViewFavoritesListInDifferentUsers](https://testray.liferay.com/home/-/testray/case_results/2059045161)

[ContentPagesUI#ViewFavoriteFragmentIsHiddenWhenItIsNotAllowedOnMasterPage](https://testray.liferay.com/home/-/testray/case_results/2059042680)

[PagesTreeWithStaging#CanReorganizePagesViaPageFinderInStagingSiteNotInLiveSite](https://testray.liferay.com/home/-/testray/case_results/2059039831)

OBS: se precisar de ajuda pra entender onde eles falham eh so pedir :)

**Comment by rafaprax** [comment]
ci:help

**Pull request closed without merging**
