### PR TITLE
LPS-78556 Use associated input localized instead of deprecated translation manager

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Hey @pavel-savinov , I'm facing a little issue with your PR.

I try to add a Basic Web Content in Web Content Portlet and I get this error in console:

```
Uncaught TypeError: Cannot read property 'getHTML' of undefined
    at component.getValue (ddm_form.js?browserId=other&minifierType=&languageId=en_US&b=7100&t=1520858809803:2830)
    at component.syncValueUI (ddm_form.js?browserId=other&minifierType=&languageId=en_US&b=7100&t=1520858809803:747)
    at component.renderUI (ddm_form.js?browserId=other&minifierType=&languageId=en_US&b=7100&t=1520858809803:365)
    at YUI.<anonymous> (array-invoke.js:32)
    at Array.forEach (<anonymous>)
    at Function.YArray.each.YArray.forEach (aui.js:2522)
    at Function.Y.Array.invoke (array-invoke.js:30)
    at component.renderUI (ddm_form.js?browserId=other&minifierType=&languageId=en_US&b=7100&t=1520858809803:3138)
    at component.initializer (ddm_form.js?browserId=other&minifierType=&languageId=en_US&b=7100&t=1520858809803:3132)
    at component._initHierarchy (base-core.js:774)
```

The exact spot of the problem is:

`return isNode(editor) ? A.one(editor).val() : **editor.getHTML();**` in getValue() from ddm_form.js.

Can you take a look at that? Thanks!

**Pull request closed without merging**
