### PR TITLE
LPS-81608 Edit alert message

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
Please run buildLang

**Comment by pedroqueiroz** [comment]
Sent to BChan at https://github.com/brianchandotcom/liferay-portal/pull/60210.

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/inacionery/liferay-portal/pull/718. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/8d81c00b8f1d~2...8d81c00b8f1d)

**Pull request closed without merging**
