### PR TITLE
LPS-107777 | LPS-110287 Build lang

### PR DESCRIPTION
**Pull request by albinojunior**

### CODE REVIEW

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
ci:test:stable

**Comment by rafaprax** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/inacionery/liferay-portal/pull/593. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/de537cb38566~2...de537cb38566)

**Pull request closed without merging**
