### PR TITLE
LPS-75410 Add unit tests

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rodrigopaulino** [comment]
Hey, @pedroqueiroz.

Could you please check these following behaviors:
1. With an empty field, if the first character I type is ".", the field automatically transforms its value to "0._";
2. First input some number with decimal value to the field, let's say "123.45". If I try to type another ".", the original decimal symbol is moved to the position where the cursor is, only if that position is **behind** the original position of the decimal symbol. If not, the decimal symbol stays at its original position;
3. Prior to this issue, I was able to see the thousands separator, but now It's not being added. Similar to that, I'm only able to enter 2 decimal places to that number instead of 6 as it was before. Is this documented?

**Comment by clovisdasilvaneto** [comment]
LGTM!

**Comment by clovisdasilvaneto** [comment]
@rodrigopaulino for the points 1 and 2, this is a default behavior of the mask input plugin that we are using.

If it it doesn't work with the forms usability, I guess we should try another mask plugin, but it's hard to find another plugin that is attending the requisites of liferay-amd-module-loader plugin.

**Comment by pedroqueiroz** [comment]
I got some answer from Jadson:

1. He is ok with this behavior.
2. He did not like this behavior, the second "," or "." should be blocked.
3. It should not have decimal limit.

**Pull request closed without merging**
