### PR TITLE
[TECHNICAL-SUPPORT] LPS-85915

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @diana-lin 

Relevant tickets:
https://issues.liferay.com/browse/LPS-85915

Notes from Diana:
> Problem:  Required fields which have been skipped from Form Rules remain marked as required when they are imported.  This causes a `RequiredValue` exception to be thrown.
> 
> Context:  On Form submission, required fields which have been skipped have their `required` property updated to `false`.  This same update should be imposed on Form import.
> 
> Solution:  Update Form fields to required/not required on import.  Since the functionality of `AddFormInstanceRecordMVCCommandHelper.updateRequiredFieldsAccordingToVisibility(...)` will be used in both the `dynamic-data-mapping-form-web` and `dynamic-data-mapping-service` modules, we propose creating a service.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by rafaprax** [comment]
Hi @diana-lin , I'm going to review this today afternoon.

Sorry for the delayed response.

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Hi @diana-lin , I fixed this issue using other approach. I'm skipping the formValues validation in the export/import process.

Let me know if you have any doubts. Thx

**Pull request closed without merging**
