### PR TITLE
LPS-80252 Add a specific class to form entry style

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Hey @alinedoleron you are including commits from https://github.com/rafaprax/liferay-portal/pull/579 pr in this one. Is this intentional? Please fix it.

Thx

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
LGTM @alinedoleron

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Sent to BChan https://github.com/brianchandotcom/liferay-portal/pull/58184.

**Pull request closed without merging**
