### PR TITLE
LPS-82171 Update tests

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Hi @vicnate5, can you please test this?

Thx

**Comment by rafaprax** [comment]
ci:stop

**Comment by rafaprax** [comment]
ci:stop

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
Rebased and resent at: https://github.com/rafaprax/liferay-portal/pull/765.

**Pull request closed without merging**
