### PR TITLE
LPS-84096 Fix Kaleo test

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
ci:test:sf

**Comment by pedroqueiroz** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
Pull request forwarded to https://github.com/jeyvison/liferay-portal/pull/176. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
