### PR TITLE
LPS-106125 Change SLA status to completed if completion date is not null

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:test:sf

**Comment by inacionery** [comment]
ci:test:relevant

**Comment by inacionery** [comment]
ci:test:workflow

**Comment by rafaprax** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84117. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/a5bab041384b~3...a5bab041384b)

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84119. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/c73fa4c76325~3...c73fa4c76325)

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84187. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/3ed127ecf7ae~3...3ed127ecf7ae)

**Pull request closed without merging**
