### PR TITLE
LPS-78539 Add a method to return the predefined value of a field

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
hey @vicnate5, I think this is good to go. What do you think?

**Comment by vicnate5** [comment]
@pedroqueiroz No, all test failures here seem to be unique, and different :(

**Comment by pedroqueiroz** [comment]
@vicnate5  oh boy :(

**Comment by vicnate5** [comment]
@pedroqueiroz @marcelabc It isn't as bad as I thought. There were some changes over the weekend.

The only unique issue here is that the field `name` is reset when user does a "Change Field Type"

Is this the new expected behavior?

**Comment by vicnate5** [comment]
resetname

**Comment by pedroqueiroz** [comment]
Oops, no, it's not. :( @vicnate5

**Comment by pedroqueiroz** [comment]
Sent to @marcelabc  at https://github.com/marcelabc/liferay-portal/pull/1.

**Pull request closed without merging**
