### PR TITLE
LPS-78530 Add getter for context property in field type paragraph

### PR DESCRIPTION
**Pull request by clovisdasilvaneto**

### CODE REVIEW

**Comment by clovisdasilvaneto** [comment]
ci:test

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
screen shot 2018-03-26 at 4 30 25 pm

Hey @clovisdasilvaneto, after your changes, the data bind for the paragraph's text is not working. Could you please take a look on that? Thx

**Comment by clovisdasilvaneto** [comment]
Hmm that's ok prax, I'll take a look in this PR

**Comment by clovisdasilvaneto** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:reopen

**Pull request closed without merging**
