### PR TITLE
LPS-77034 setting default currentTab to 'forms'

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test

**Comment by linolaoj** [comment]
ci:reopen

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/pedroqueiroz94/liferay-portal/pull/46. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/c2d383f531c2~1...c2d383f531c2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
