### PR TITLE
LPS-77053 SF

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
@rafaprax , can you just review code style? The tests are ok in https://github.com/pedroqueiroz/liferay-portal/pull/124.

You can send to BChan if it's ok for you. 

Thanks!

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56666. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/58ddb58bfaba~1...58ddb58bfaba) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56829. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/b4b148786012~1...b4b148786012) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
