### PR TITLE
LPS-76142 Build lang

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Hi @vicnate5, Can we cover this with a poshi test?

After these changes, when a user click on publish/unpublish button we are adding the message `Saved on ...` in the autosave bar.

Thx

**Comment by pedroqueiroz** [comment]
LGTM! :)

**Comment by vicnate5** [comment]
Will cover in poshi https://issues.liferay.com/browse/LRQA-40383

**Comment by rafaprax** [comment]
sent to BChan at https://github.com/brianchandotcom/liferay-portal/pull/57618

**Pull request closed without merging**
