### PR TITLE
[TECHNICAL-SUPPORT] LPS-85952

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @brianikim 

Notes from Brian:

> https://issues.liferay.com/browse/LPS-85952
> 
> My PR from #499 that links https://issues.liferay.com/browse/LPS-85600 is not correct. Although LPS-85600 is related to LPS-85952, they are two separate bugs.
> 
> The issue here is that whenever you try to save a form with its page name and description filled in and you fail any form validation checks during the submit, the page will refresh and the form content will be reset for page names and descriptions.
> 
> The fix is to ensure that we pass in localizedDescription and localizedTitle to the back-end as page name and description are handled under the mentioned two specific variable names.
> 
> Please let me know if you have any questions. Thanks.
> 
> Sincerely,
> Brian Kim

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by SamZiemer** [comment]
ci:retest:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
Hello @rafaprax ,

Any updates on this review? Thanks.

Sincerely,
Brian Kim

**Comment by rafaprax** [comment]
@alinedoleron
Can you please help me with this review? 

Thx
//cc @brianikim

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
LGTM

**Comment by rafaprax** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/63864. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
