### PR TITLE
[TECHNICAL-SUPPORT] LPS-99385

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:search

**Comment by rafaprax** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/76754. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/964. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/96b0e23950a5~1...96b0e23950a5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
