### PR TITLE
LRQA-39495 Modified macro to click and type instead of only type

### PR DESCRIPTION
**Pull request by rigosouza**
> Hey @pedroqueiroz!
>
>I fixed system settings test to be according to the new UI, but the other two failures seem to be related to this PR. Both happen on Site Pages:
>
>1- Next button does not work when you have pagination
>2- Submit button is disabled and can not be clickable

//cc @clovisdasilvaneto

### CODE REVIEW

**Comment by rigosouza** [comment]
Closed by mistake, reopened now

**Comment by rafaprax** [comment]
[https://github.com/rafaprax/liferay-portal/pull/413#issuecomment-374943847](url)

**Comment by rigosouza** [comment]
ci:test

**Comment by clovisdasilvaneto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Resent at https://github.com/rafaprax/liferay-portal/pull/445.

**Pull request closed without merging**
