### PR TITLE
LPS-106224 In Calendar If you un-check 'All Day' the start time is always hours later

### PR DESCRIPTION
**Pull request by knchau**
https://issues.liferay.com/browse/LPS-106224

I changed the steps to show the defaulted time discrepancy between the 'Add Event' button and clicking any day with 'All Day' unchecked. 

**Issue:**
In the Calendar Widget, when in the 'Month' view if you click on a day and add an event then uncheck "All Day", the default starting time of the event is set to UTC timezone even though the calendar is set to a different timezone.

**Solution:**
I removed setting "All Day" events to default to UTC timezone. This change would make the defaulted time zone match the user's/calendar's configured time zone, resulting in default hour's time to be as close to the user's current hour.

### CODE REVIEW

**Comment by knchau** [comment]
ci:test:sf

**Comment by knchau** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
sent to BChan at https://github.com/brianchandotcom/liferay-portal/pull/82537

**Pull request closed without merging**
