### PR TITLE
LPS-81362 returning options

### PR DESCRIPTION
**Pull request by linolaoj**
cc: @andreldm

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
LGTM

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
sent to https://github.com/brianchandotcom/liferay-portal/pull/58922

**Pull request closed without merging**
