### PR TITLE
LPS-77519 Creating macro to click on Enviar button

### PR DESCRIPTION
**Pull request by rodrigo-e-c-souza**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
@rodrigo-e-c-souza Test fix looks good. We should run tests here. 

Will retest after compile error is fixed at head.

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:reopen

**Comment by rodrigo-e-c-souza** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
Resent at https://github.com/rafaprax/liferay-portal/pull/315.

**Comment by rodrigo-e-c-souza** [comment]
ci:stop

**Pull request closed without merging**
