### PR TITLE
LPS-83602 adding permission when resource has composite name

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
Hello,
https://issues.liferay.com/browse/LPP-30892 is also waiting on this PR. Thanks for making this fix.

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
Hey @linolaoj , the code looks good to me. I will just wait for the `ci:test` to run to see if we have any negative impact on Web Content. After that, I will forward this to BChan. Thanks!

**Comment by pedroqueiroz** [comment]
Not covering this with tests, since it is a legacy module.

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Sent to BChan at https://github.com/brianchandotcom/liferay-portal/pull/61729

**Pull request closed without merging**
