### PR TITLE
LPS-80478 SF

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Hey @vicnate5, We are getting the failure `LocalFile.Forms#ReorderFieldOptions` in all pull requests. I've tried reproduce it locally but I could not. Can you reproduce it or can you help me to reproduce it?

Thx

**Comment by vicnate5** [comment]
@rafaprax Fix sent https://github.com/brianchandotcom/liferay-portal/pull/58404

Had the same problem, could not originally reproduce locally. Added a workaround.

**Comment by rafaprax** [comment]
Thanks @vicnate5

**Pull request closed without merging**
