### PR TITLE
LPS-70635 BuildLang

### PR DESCRIPTION
**Pull request by pedroqueiroz94**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
ci:reopen

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
ci:stop

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by rafaprax** [comment]
@pedroqueiroz94 please resend. rebase issues

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/48638. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
