### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:stop

**Comment by rafaprax** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
@rafaprax , can you please rebase?

**Comment by rafaprax** [comment]
It's already merged

**Pull request closed without merging**
