### PR TITLE
LPS-77818 fix delete button css

### PR DESCRIPTION
**Pull request by linolaoj**
cc: @alinedoleron , @clovisdasilvaneto

### CODE REVIEW

**Comment by rafaprax** [comment]
@clovisdasilvaneto @alinedoleron Could you please give me your "LGTM" for this pr? Thx :)

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
LGTM

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56516. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
