### PR TITLE
LPS-79447 Build Lang

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
hey @vicnate5, we might need to fix/add tests for validation

**Comment by vicnate5** [comment]
Taking a look

**Comment by rafaprax** [comment]
LGTM

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@pedroqueiroz Sorry for the delay.

I rebased to the latest update here

Forwarded to https://github.com/rafaprax/liferay-portal/pull/596 with test fix.

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
