### PR TITLE
LPS-80084 Add integration test

### PR DESCRIPTION
**Pull request by andreldm**

### CODE REVIEW

**Comment by andreldm** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@rafaprax as an FYI, the test that failed here `LocalFile.FormRules#ConfigureCalculateRule` is an intermittent bug where the Form page portlet will not render. You might see the test randomly fail on other pulls. The other tests that sometimes fails due to this bug is `FormRules#ConfigureUserBelongsToRule`. I been trying to reproduce locally, but nothing so far :(

CC @pedroqueiroz

**Comment by rafaprax** [comment]
@vicnate5 I'll try to reproduce here. I took a look at the report and somehow there is no a approved version for that Form. weird

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57997. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/65d82d2e5688~1...65d82d2e5688) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
