### PR TITLE
LPS-102368 Does not remove row when the index value is the same as th…

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @knchau

Notes from Kim:
> https://issues.liferay.com/browse/LPS-102368
> Fix merged into master: https://github.com/brianchandotcom/liferay-portal/pull/79165
> 
> This fix changes the operator to include the `=`, so that an index value that is the same as the number of weeks would be removed because index starts at 0 whereas the number of week count starts at 1.
> 
> Also needs to include an update to the Alloy version when [AUI-3182](https://issues.liferay.com/browse/AUI-3182) is merged into alloy-ui master since that fix is also needed for this ticket.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
@rafaprax do you have an ETA of when you may be able to review this?

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79569. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
