### PR TITLE
LPS-79494 Update test locator to account for both field types

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Hey @vicnate5 , I'm not sure if the `LocalFile.Forms#AddElementSetsWithTranslation` fail is caused by this pr. Can you please check it?

Thx

**Comment by vicnate5** [comment]
@rafaprax It is OK. This is an intermittent failure on this test.

**Comment by rafaprax** [comment]
Thx @vicnate5

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Sent to BChan at https://github.com/brianchandotcom/liferay-portal/pull/59171.

**Pull request closed without merging**
