### PR TITLE
LPS-79184 Add integration tests

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
hey @vicnate5, is this good to go? thanks!

**Comment by vicnate5** [comment]
@pedroqueiroz LGTM

**Comment by pedroqueiroz** [comment]
LGTM

**Comment by rafaprax** [comment]
sent to BChan at https://github.com/brianchandotcom/liferay-portal/pull/59497

**Pull request closed without merging**
