### PR TITLE
LPS-77064 Fix hover color on select field to be the same of Clay

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test

**Comment by alinedoleron** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by clovisdasilvaneto** [comment]
LGTM!

**Comment by pedroqueiroz94** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/54901

**Pull request closed without merging**
