### PR TITLE
LPS-82719 Include dependency of liferay-util-window on ddm_form.js

### PR DESCRIPTION
**Pull request by rodrigopaulino**

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
There are no changes made in Forms. Failures must be related to something other than this pull.

**Comment by rafaprax** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/60609. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/759eb77dcd75~2...759eb77dcd75) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
