### PR TITLE
LPS-82324 Rename method

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
LGTM

**Comment by pedroqueiroz** [comment]
Hey @vicnate5, can you take a look at this PR? Thanks!

**Comment by vicnate5** [comment]
@pedroqueiroz LGTM, Test failures are known issues, and this fixes the workflow definition bug.

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Thanks, @vicnate5. Sent to BChan at https://github.com/brianchandotcom/liferay-portal/pull/61119.

**Pull request closed without merging**
