### PR TITLE
Lps 109221

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @brianikim

Notes from Brian:
> https://issues.liferay.com/browse/LPS-109221
> 
> See ticket for issue description.
> 
> Solution is to ensure the calendarResource for a guest user is not updated.
> 
> The solution is consistent with the behavior introduced from https://github.com/liferay/liferay-portal/commit/151a7ca13f40dea2628523fefcbaec82e36fe465#diff-5ca8bc460cc7c74517a366a5622918f5 in which only a user name change warrants a calendarResource update. Guest users will never have their name values changed as it will always be "Guest".
> 
> Please let me know if you have any questions. Thanks.
> 
> Sincerely,
> Brian Kim
>

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/85620.

**Pull request closed without merging**
