### PR TITLE
LPS-79494 Correct the numeric tests due to the addition of the setValidationDataType method

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Hey girls @marcelabc @alinedoleron There is a related issue here `LocalFile.Forms_SubmitFormWithCustomTextContainingValidation/summary.html.gz`

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
resent to https://github.com/rafaprax/liferay-portal/pull/660

**Pull request closed without merging**
