### PR TITLE
LPS-74847 If the ' -condition-first-operand ' is a repeatable field, the only options available for the '-condition-operator' field are: 'is-empty' or 'not-is-empty'. Otherwise, all options are available.

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
SF and resent at https://github.com/rafaprax/liferay-portal/pull/705.

**Pull request closed without merging**
