### PR TITLE
WIP

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:help

**Comment by rafaprax** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
vou rodar as suites de novo pra ver se esses testes passam:
[PortalSmokeUpgrade#ViewPortalSmokeArchive7413](https://testray.liferay.com/home/-/testray/case_results/2399022456?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F1575876400%2Fview%3FtestrayCaseId%3D1575876400%26cur%3D2%26delta%3D200%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc%26resetCur%3Dfalse)
[WebContentWithCustomStructures#AddWebContentBasedOnStructureKeyWithAmpersand](https://testray.liferay.com/home/-/testray/case_results/2398924921?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F1956680484%2Fview%3Fcur%3D1%26delta%3D200%26testrayCaseId%3D1956680484%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc)

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
ci:test:sf

**Pull request closed without merging**
