### PR TITLE
LPS-77347 Improves memory leaking

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Hey @vicnate5, Are these errors related to this pr? Thx

**Comment by vicnate5** [comment]
@rafaprax @brunobasto Many unique issues on this pull.

**1. Trouble changing field types**
changedatefield

**2. Email Notification fields do not load** 
screenshot 2018-04-30 10 58 33

**3. Trouble changing field label**
changelabel

**4. Autofill for Select from List from Data Provider did not work**

If you need more details about any of these, please let me know.

**Comment by rafaprax** [comment]
Thx @vicnate5

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Resent at https://github.com/rafaprax/liferay-portal/pull/576.

**Pull request closed without merging**
