### PR TITLE
LPS-81584 Apply Clay select field to Validation options

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Hey @alinedoleron , there is a related fail here `LocalFile.Forms#SubmitFormWithCustomTextContainingValidation`. I think we just need to update the path that points to `select` in the validation field.

//cc @vicnate5

**Comment by vicnate5** [comment]
yea, looks like a path issue.

**Comment by alinedoleron** [comment]
Hi @vicnate5, this Poshi error happens because we removed the browser's `<select>` and now we use the Form's select.

**Comment by vicnate5** [comment]
@alinedoleron Got it. I should probably fix this one. Will send.

**Comment by vicnate5** [comment]
https://github.com/rafaprax/liferay-portal/pull/756

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
