### PR TITLE
LPS-80478

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
LGTM

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/612. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/a3dda5df6843~1...a3dda5df6843) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
