### PR TITLE
LPS-103242 Fix duplicated requests on performance by step and by assignee cards

### PR DESCRIPTION
**Pull request by albinojunior**

### CODE REVIEW

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
already sent and merged into master, see https://github.com/brianchandotcom/liferay-portal/pull/81507

**Pull request closed without merging**
