### PR TITLE
LPS-113305 SF

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:forward

**Comment by marianoalvarosaiz** [comment]
Hi @rafaprax,

 the SF can be risky because it implies retrieving `PortalUtil.getClassNameId(_CLASS_NAME_CAL_EVENT)` after it has been deleted in _deleteCalEventClassName_. If so, we should probably save its value in a variable.

Kind regards.

**Comment by rafaprax** [comment]
Ol @marianoalvarosaiz , I will fix the SF commit. Thanks for catch this early.

**Comment by rafaprax** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/1042. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/8b3236bc335e~1...8b3236bc335e)

**Pull request closed without merging**
