### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test

**Comment by alinedoleron** [comment]
LGTM

**Comment by alinedoleron** [comment]
ci:test

**Comment by pedroqueiroz94** [comment]
LGTM

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
LGTM!

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
Hey @marcelabc , please, can you take a look at this issue? It looks weird when rendered in Form Builder (See screenshot below).

screen shot 2018-02-07 at 4 53 47 pm

Also, can you apply the clay markups to the ddm-type-checkbox module? 

Thanks!

**Comment by pedroqueiroz94** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
@marcelabc Please rebase and fix the conflicts. Thx

I tried fix using the github tool but It didn't work.

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
Resent at https://github.com/rafaprax/liferay-portal/pull/349.

**Pull request closed without merging**
