### PR TITLE
LPS-79277 Retrieving serializedFormBuilderContext from right request

### PR DESCRIPTION
**Pull request by rodrigopaulino**

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rodrigopaulino** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rodrigopaulino** [comment]
Sent to BChan https://github.com/brianchandotcom/liferay-portal/pull/58206

**Pull request closed without merging**
