### PR TITLE
LPS-73253 Prevent exception, since text field can have either an input or a textarea

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
Test ran at https://github.com/alinedoleron/liferay-portal/pull/19, it seems good. :)

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57916. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/8dc2b0605106~2...8dc2b0605106) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
