### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
@vicnate5 , can we cover this use case with a poshi test? :)

**Comment by rafaprax** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
ci:stop

**Comment by vicnate5** [comment]
@pedroqueiroz https://issues.liferay.com/browse/LRQA-39549

**Pull request closed without merging**
