### PR TITLE
LPS-71870 Apply Clay classes to truncate label with big text

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
@alinedoleron , @rafaprax can you guys fix the first commit message? Thanks!

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
PR sent to BChan at https://github.com/brianchandotcom/liferay-portal/pull/57932.

**Pull request closed without merging**
