### PR TITLE
LPS-77168 formatJavadoc

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
ci:test

**Comment by inacionery** [comment]
ci:reopen

**Comment by inacionery** [comment]
ci:retest

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/275. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54956. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
