### PR TITLE
LPS-78362 Apply navigation and management bar to DDM Form Browser

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/58501. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/58625. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/6453b4ae6e11~1...6453b4ae6e11) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
