### PR TITLE
[TECHNICAL-SUPPORT] LPS-81935

### PR DESCRIPTION
**Pull request by JosemariaMunoz**
https://issues.liferay.com/browse/LPS-81935

### CODE REVIEW

**Comment by JosemariaMunoz** [comment]
ci:test

**Comment by JosemariaMunoz** [comment]
ci:reopen

**Comment by JosemariaMunoz** [comment]
Hi @rafaprax,

I think this failures are related to these known issues: [feed/11955568](https://loop.liferay.com/home/-/loop/feed/11955568). 

Also, I did several tests over my own branch and I got different failures: first tests failures are related to [feed/11941378](https://loop.liferay.com/home/-/loop/feed/11941378), and second ones to [feed/11955568](https://loop.liferay.com/home/-/loop/feed/11955568).

Please let me know if I can help with anything.

Thanks!

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JosemariaMunoz** [comment]
Hey @pedroqueiroz ,
Just tell me if you need any information or help about this PR.
Thanks!

**Comment by pedroqueiroz** [comment]
Hi @JosemariaMunoz , thank you for the PR! 

It seems everything is ok, but I think there is room for an integration test. Do you mind writing one?

Thank you a lot! :)

**Comment by JosemariaMunoz** [comment]
Hi @pedroqueiroz ,
Sure thing, no problem! thanks for the advice!

**Comment by pedroqueiroz** [comment]
Thank you, @JosemariaMunoz ! :)

I'm closing this and wait for your next PR, ok?

Thanks a lot!

**Comment by JosemariaMunoz** [comment]
Perfect, thanks @pedroqueiroz !  👍

**Pull request closed without merging**
