### PR TITLE
LPS-81978 Deal with tab changes

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test:sf

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
LGTM!

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
https://github.com/rafaprax/liferay-portal/pull/720

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
