### PR TITLE
LPS-72402 Clean option value when user interacts with field

### PR DESCRIPTION
**Pull request by clovisdasilvaneto**

### CODE REVIEW

**Comment by clovisdasilvaneto** [comment]
ci:test

**Comment by clovisdasilvaneto** [comment]
ci:stop

**Comment by clovisdasilvaneto** [comment]
ci:retest

**Comment by pedroqueiroz** [comment]
@clovisdasilvaneto , SF error here. Can you fix?

**Comment by rafaprax** [comment]
Hey @clovisdasilvaneto, please run the Forms functional tests? Thx

**Pull request closed without merging**
