### PR TITLE
LPS-87070 Fix the tests to allow general language key overwrite the language in forms

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
LGTM

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/64995. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
