### PR TITLE
LPS-174952 Update the workflow definition XSD to support the new update status action in places where the script action is supported

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: [LPS-174952](https://issues.liferay.com/browse/LPS-174952)

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:forward

**Comment by rafaprax** [comment]
Hey @catarineaguiar, Can you please help scan these test results? If everything is ok, could you please forward it manually to BChan?

Thx

**Comment by catarineaguiar** [comment]
Sure @rafaprax, I'm going to run workflow test suite to make sure it didn't caused any regression.

**Comment by catarineaguiar** [comment]
ci:test:workflow

**Comment by catarineaguiar** [comment]
no regressions found. Forwarding manually.

**Comment by catarineaguiar** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/130173

**Comment by catarineaguiar** [comment]
ci:close

**Pull request closed without merging**
