### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
@pedroqueiroz94 After the tests run, can you please take a look on this changes about the LPS-77725?

Thx

**Comment by pedroqueiroz94** [comment]
@rafaprax , LGTM :)

**Comment by rafaprax** [comment]
sent to Preston Crary

**Pull request closed without merging**
