### PR TITLE
LPS-81563 No longer needed

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test:sf

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
hey @vicnate5, I don't think these extra failures are related. Do you agree? Thanks!

**Comment by vicnate5** [comment]
The only one that looks unique is `LocalFile.Forms#CreateUntitledForm`, but it could be a fluke since your code didn't touch that area.

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:reopen

**Comment by pedroqueiroz** [comment]
Sent to BChan at https://github.com/brianchandotcom/liferay-portal/pull/61765.

**Pull request closed without merging**
