### PR TITLE
LPS-171867 Remove "immediate = true" from headless pt 2

### PR DESCRIPTION
**Pull request by GabrielHenriquedev**

### CODE REVIEW

**Comment by GabrielHenriquedev** [comment]
ci:test:sf

**Comment by GabrielHenriquedev** [comment]
ci:test:relevant

**Comment by GabrielHenriquedev** [comment]
ci:test:headless

**Comment by rafaprax** [comment]
forwarded to core-infra repo https://github.com/liferay-core-infra/liferay-portal/pull/3047

**Pull request closed without merging**
