### PR TITLE
LPS-81709 Form language selector will still show unavailable language if language is removed from portal

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
@vicnate5, is this good to go? Thanks!

**Comment by pedroqueiroz** [comment]
LGTM

**Comment by vicnate5** [comment]
LGTM @pedroqueiroz

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Sent to BChan at https://github.com/brianchandotcom/liferay-portal/pull/59697.

@rafaprax , can you send a follow up request with the unit test we were talking about? Thanks!

**Pull request closed without merging**
