### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
ci:stop

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
@MichaelPrigge , I will have to take a deeper look at this. I will tag you when I send a new PR, okay? :)

**Comment by MichaelPrigge** [comment]
@pedroqueiroz that sounds good and thank you for looking into this deeper. I'd definitely appreciate it if you would tag me on your next PR for this too. 

This issue is currently a blocker for a client in Support so it's definitely a higher priority for us.

Thanks again for your help!

**Comment by joshuacords** [comment]
Hello @MichaelPrigge  or @pedroqueiroz, has there been any progress made on this PR. LPS-73350 and LPS-79104 are dependent on this.

**Comment by pedroqueiroz** [comment]
Hi, @joshuacords . It has already been merged:

https://github.com/brianchandotcom/liferay-portal/pull/56540
https://github.com/brianchandotcom/liferay-portal/pull/56610
https://github.com/brianchandotcom/liferay-portal/pull/56674

Thanks! :)

**Comment by joshuacords** [comment]
Oh - thanks @pedroqueiroz! @MichaelPrigge, do you mind updating BPR-14977?

**Pull request closed without merging**
