### PR TITLE
LPS-76355 Remove icon-monospaced class

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
Resent at https://github.com/pedroqueiroz94/liferay-portal/pull/50.

**Comment by pedroqueiroz94** [comment]
Resent at https://github.com/pedroqueiroz94/liferay-portal/pull/50.

**Pull request closed without merging**
