### PR TITLE
LPS-79447 SF

### PR DESCRIPTION
**Pull request by rodrigopaulino**
cc @pedroqueiroz

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Hey, @vicnate5. Could you please check if the Validation failed test needs to be updated?
Thanks.

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
Forwarded to https://github.com/rafaprax/liferay-portal/pull/625

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
