### PR TITLE
LPS-79618 adding journal article cell editor

### PR DESCRIPTION
**Pull request by linolaoj**
cc: @alinedoleron , @andreldm

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:reopen

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:test:releveant

**Comment by rafaprax** [comment]
Hey @linolaoj Can you please add some information about the Web Content at the `JournalArticleCellEditor ` when selecting a Web Content? 

The  `DocumentLibraryCellEditor` does something similar to this.

Thx

**Comment by linolaoj** [comment]
changes pushed

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/58919. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
