### PR TITLE
LPS-86420: Replace _.forEach with native Array.prototype.forEach

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test

**Comment by julien** [comment]
ci:reopen

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by julien** [comment]
Hi @rafaprax,

Could you test these changes locally and tell me your thoughts, we're replacing lodash (in this case `_.forEach`) with the native functions.

Thanks!

**Comment by julien** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/64647

**Pull request closed without merging**
