### PR TITLE
LPS-80078 Create sidebar_navigation template

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
Hi @victorware, the markup change. I applied the component-tbar of Lexicon. Please, can you take a look at this? Let me know if you need some clarification.

**Comment by vicnate5** [comment]
Resent https://github.com/rafaprax/liferay-portal/pull/607

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
