### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
hey @rafaprax , can you check if the data provider portlet title is correct? It should be "Data Providers". Thanks!

**Comment by pedroqueiroz** [comment]
I think we can cover this with poshi tests. @vicnate5 , what do you think?

**Comment by vicnate5** [comment]
@pedroqueiroz We can cover with poshi, I think 1 test for this and https://issues.liferay.com/browse/LPS-79184

https://issues.liferay.com/browse/LRQA-39645

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56635. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/65a014e54030~3...65a014e54030) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56636. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/5eb1c5c14b9b~4...5eb1c5c14b9b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
