### PR TITLE
LPS-99154 Subject of email notifications for calendar event invitations display escaped special characters

### PR DESCRIPTION
**Pull request by IstvanD**
Hi @rafaprax 

Could you please review this pull request?

Thank you and best regards,
István

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
ci:repoen

**Comment by IstvanD** [comment]
ci:repoen

**Comment by IstvanD** [comment]
ci:repoen

**Comment by IstvanD** [comment]
ci:reopen

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76518. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
