### PR TITLE
LPS-82410 Modify the test to increase the complexity

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/769. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/f955e25cb2f5~2...f955e25cb2f5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/61212. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/c695c212d3f0~1...c695c212d3f0) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
