### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
@rigosouza, can you take a look at this? Thanks!

**Comment by rigosouza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/413. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/81eca7f5fd53~1...81eca7f5fd53) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
