### PR TITLE
LPS-84011 Since we intend to test Forms, it is not necessary to enable Staging for DDL and DL by now

### PR DESCRIPTION
**Pull request by pedroqueiroz**
hey @vicnate5 , I made some changes to your PR. I tried to explain my motivation in each commit, but let me know if you have any further questions. :)

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test:sf

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@pedroqueiroz Thanks! your comments are clear. Regarding DL and DDL, We will need these in future test scenarios (See LPS-84019, LPS-84021, LPS-84022, LPS-84012). Maybe not DDL since it is fully decoupled, right?

Though in this scope of this test, we don't need them, we can add later.

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:reopen

**Comment by pedroqueiroz** [comment]
Yeah, @vicnate5 , we're investigating that :/

**Comment by pedroqueiroz** [comment]
Hey @vicnate5 , we had to change the approach for this test. Can you take a look, specially in my first commit? Thanks!

**Comment by pedroqueiroz** [comment]
ci:test:sf

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@pedroqueiroz Great. I like this. I was thinking about something similar as another way to test this behavior.

**Comment by vicnate5** [comment]
Semver. Should we move the Util class to the same module?

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
Sent to BChan at https://github.com/brianchandotcom/liferay-portal/pull/62039.

**Pull request closed without merging**
