### PR TITLE
LPS-84111 Add unit test

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test:sf

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
hey @vicnate5, can we add a poshi test for this?

**Comment by vicnate5** [comment]
https://issues.liferay.com/browse/LRQA-43072

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
ci:stop

**Comment by rafaprax** [comment]
LGTM

**Comment by pedroqueiroz** [comment]
Sent to BChan at https://github.com/brianchandotcom/liferay-portal/pull/62355.

**Pull request closed without merging**
