### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test

**Comment by vicnate5** [comment]
@alinedoleron On this pull, the new search bar causes some weird behavior.

There is always a scroll left/right in the Rules dropdowns. The Search icon is never visible unless you scroll right.

Is there anything you can do to fix this?


rulesvisuals

CC @rodrigo-e-c-souza

**Comment by alinedoleron** [comment]
Hi @vicnate5, this issue only happens on Firefox. We created an issue today for this. https://github.com/liferay/clay/issues/516.

**Comment by vicnate5** [comment]
@alinedoleron Thanks for the quick response. Chrome does looks good :)

**Comment by vicnate5** [comment]
Sent to @alinedoleron https://github.com/alinedoleron/liferay-portal/pull/3

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
