### PR TITLE
LPS-86551 Move upgradePortletId processes to web module

### PR DESCRIPTION
**Pull request by achaparro**
Hay @rafaprax,

We have moved the processes which upgrade the portletId to the web module since it is part of the web logic. Otherwise we could get the issue explained here: https://issues.liferay.com/browse/LPS-86551

Thanks!

cc/  @jcampoy

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Tests seem unrelated, right @rafaprax?

cc/ @jcampoy

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
The message "This pull contains no unique failures." confirms it.

**Comment by rafaprax** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/64677. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/2b2216acc5b4~1...2b2216acc5b4) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
