### PR TITLE
LPS-187216 Remove POP3 checkbox that enables the use of OAuth to POP3 connections

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
Unable to test right now due to issue with the IT ms exchange account.

**Pull request closed without merging**
