### PR TITLE
LPS-66490 - [Poshi Test] Modify the existent test of captcha field to make it cover the scenario of a published form.

### PR DESCRIPTION
**Pull request by natocesarrego**
cc @vicnate5

### CODE REVIEW

**Comment by natocesarrego** [comment]
Closing PR for now, because CI reported some broken tests. As soon as I fix it, I'll reopen.

Thanks.

**Comment by natocesarrego** [comment]
ci:stop

**Comment by natocesarrego** [comment]
ci:retest

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/vicnate5/liferay-portal/pull/486. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/2f7c1cb~2...2f7c1cb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56470. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/98048ebcf869~1...98048ebcf869) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
