### PR TITLE
LPS-79260 Expose Form Services with permission check to be consumed by APIO

### PR DESCRIPTION
**Pull request by victorlaerte**

### CODE REVIEW

**Comment by victorlaerte** [comment]
ci:test

**Comment by victorlaerte** [comment]
ci:reopen

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/464. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/5d92c57417e1~1...5d92c57417e1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
