### PR TITLE
LPS-79088 Fix margin top according to view port

### PR DESCRIPTION
**Pull request by clovisdasilvaneto**

### CODE REVIEW

**Comment by clovisdasilvaneto** [comment]
ci:test

**Comment by clovisdasilvaneto** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56663. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
