### PR TITLE
LPS-79730 Disable options drag and drop on sidebar and the remove option

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Rebased and resent at https://github.com/rafaprax/liferay-portal/pull/696.

**Pull request closed without merging**
