### PR TITLE
LPS-119652 | LPS-118590 Update tests

### PR DESCRIPTION
**Pull request by naraandrade**

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/liferay-workflow/liferay-portal/pull/1. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/86a0cc72df3f~1...86a0cc72df3f)

**Pull request closed without merging**
