### PR TITLE
LPS-77140 item value might be diferent from option text

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by rodrigo-e-c-souza** [comment]
ci:test

**Comment by rodrigo-e-c-souza** [comment]
ci:stop

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
Resent at https://github.com/rafaprax/liferay-portal/pull/323.

**Pull request closed without merging**
