### PR TITLE
LPS-81563 Fix tests

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test:sf

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
hey @vicnate5, can you please take a look on the poshi tests? Thanks!

**Comment by vicnate5** [comment]
@pedroqueiroz I can reproduce the regression manually using the bundle from here (https://files.liferay.com/private/bundles/test-1-5/jobs/test-portal-acceptance-pullrequest(master)/builds/2932/liferay-portal-bundle-tomcat.zip)

Data provider config:
URL: http://localhost:8080/api/jsonws/country/get-countries
User: test@liferay.com
PW: test
Timeout: 1000
OUTPUT
Label: Countries Full Name
Path: nameCurrentValue
Type: List

Steps:
1. Add the Data Provider
1. Add a new form
1. Add Select from List
1. Configure for Data Provider
1. Publish form
1. Copy URL
1. Open incognito window (guest user)
1. Navigate to URL
1. View Select from List options dropdown

**Comment by pedroqueiroz** [comment]
Thanks @vicnate5 ! Fixed and resent at https://github.com/rafaprax/liferay-portal/pull/799.

**Pull request closed without merging**
