### PR TITLE
LPS-80246 Also format number for predefined value

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test:sf

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
hey @rafaprax , I added an extra commit, but the problem we found is still there. :/ However, since it's not related to the ticket, I'm resending this.

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/739. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/e126fe0de039~1...e126fe0de039) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60712. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/549f145f1aa1~2...549f145f1aa1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60739. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/19f6d47c0696~2...19f6d47c0696) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60786. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/0f759fc3e781~3...0f759fc3e781) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
