### PR TITLE
LPS-78700 Fix unit test

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
hey @vicnate5 , are the errors related?

**Comment by vicnate5** [comment]
@pedroqueiroz it is good, failures are known issues.

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56563. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
