### PR TITLE
LPS-67623 We should deserialize documentLibrary field value when getting its content.

### PR DESCRIPTION
**Pull request by marcellustavares**
@rafaprax, could you please help me to review this fix?

There's also a failing test on this pull, see https://github.com/marcellustavares/liferay-portal/pull/1559

Thanks

### CODE REVIEW

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hey @rafaprax, @marcellustavares, @zxdgoal,

We are trying to use the standard code for images and document library instead of having a custom code for journal. We made some changes on this pull https://github.com/brianchandotcom/liferay-portal/pull/42704#issuecomment-243047379 to achieve that. I think we solved your issue as part of this changes, so you can close this one.

Regards,
Eudaldo.

**Comment by marcellustavares** [comment]
got it @ealonso, can I close the LPS as well?

**Comment by ealonso** [comment]
Hey @marcellustavares,

Yes, I've closed the related LPS.

Regards,
Eudaldo.

**Pull request closed without merging**
