### PR TITLE
LPS-86936 Use article default locale, or site default locale if new article, as the default display language.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
Hey @marianoalvarosaiz,

I saw you changed manually some generated files at your pr ([BaseHTMLTag.java](https://github.com/rafaprax/liferay-portal/pull/914/commits/a575e62b6cc4c1773cef39285c49bef51aa90aa1#diff-76944b8911745ccb46eafa6b7505535b), [init.jsp](https://github.com/rafaprax/liferay-portal/pull/914/commits/a575e62b6cc4c1773cef39285c49bef51aa90aa1#diff-96cb462b8e1a908c9bd5ead4c93b61a1) and [liferay-ddm.tld](https://github.com/rafaprax/liferay-portal/pull/914/commits/a575e62b6cc4c1773cef39285c49bef51aa90aa1#diff-63920f78c4fd24bdaaac4f2a787add82)). To fix it you need just add your new taglib attributte in [liferay-ddm.xml](https://github.com/rafaprax/liferay-portal/blob/a575e62b6cc4c1773cef39285c49bef51aa90aa1/modules/apps/dynamic-data-mapping/dynamic-data-mapping-taglib/liferay-ddm.xml) and run the `gw buildTaglibs` task.

Please fix and resend. Thx

**Comment by marianoalvarosaiz** [comment]
Thanks @rafaprax, see https://github.com/rafaprax/liferay-portal/pull/918

**Pull request closed without merging**
