### PR TITLE
LPS-72435 Build Lang

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:test

**Comment by jeyvison** [comment]
Hey @pcwhite , Can you please check these poshi failures that are happening related to workflow?  Thanks :)

**Comment by pcwhite** [comment]
@jeyvison checking now..

**Comment by pcwhite** [comment]
@jeyvison should be a simple button change test fix!

**Comment by pedroqueiroz** [comment]
@jeyvison , can you please rebase? Thanks!

**Comment by jeyvison** [comment]
@pedroqueiroz Done :)

**Comment by pedroqueiroz** [comment]
Hey @pcwhite , can you please add a poshi for this?

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/407. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/939473cbeb2c~3...939473cbeb2c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pcwhite** [comment]
@pedroqueiroz ok! https://issues.liferay.com/browse/LRQA-39483
cc @jeyvison @rafaprax

**Pull request closed without merging**
