### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests tomcat 9

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
We need to figure it out why the validator code is not being called by the JSP. We added the Date Validator anyway.

**Comment by pedroqueiroz** [comment]
Hey @vicnate5 , can we improve Upload Field poshi test to try (and fail) when typing random vales at the field? It should be disabled.

Also, for Date field, we now have a mask, so it should prevent users of typing invalid values as well.

Thanks!

**Comment by pedroqueiroz** [comment]
ci:retest

**Comment by vicnate5** [comment]
https://issues.liferay.com/browse/LRQA-40271

**Comment by linolaoj** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57423

**Pull request closed without merging**
