### PR TITLE
LPS-81978 | master

### PR DESCRIPTION
**Pull request by vicnate5**
From https://github.com/rafaprax/liferay-portal/pull/717

@pedroqueiroz

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@pedroqueiroz There is a regression showing up here. You cannot "Edit" a rule.

Steps:
1. Add 2 fields
2. Add a Show rule
3. Save form
4. Go to Rules
5. Go to "Edit" on the rule

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Thanks, @vicnate5 ! Fixed and resent at https://github.com/rafaprax/liferay-portal/pull/723.

**Pull request closed without merging**
