### PR TITLE
LPS-81596 Change question icon

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
LGTM!

**Comment by diegonvs** [comment]
Not about your pull request, but running check_sf, i've catch a error due DDMNumeric variable isn't declared. You can found it at: https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-type-numeric/src/main/resources/META-INF/resources/numeric_field.js#L80. My question is: DDMNumeric is exported globally?

**Comment by alinedoleron** [comment]
Hi @diegonvs, This variable is declared globally on numeric.es.js

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
SF and sent to BChan at https://github.com/brianchandotcom/liferay-portal/pull/59948.

**Pull request closed without merging**
