### PR TITLE
LPS-77826 ddm-web structure/template list jsp fixes

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zoltancsaszi** [comment]
ci:retest

**Comment by zoltancsaszi** [comment]
ci:stop

**Pull request closed without merging**
