### PR TITLE
[TECHNICAL-SUPPORT] LPS-85742

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Sent to BChan at https://github.com/brianchandotcom/liferay-portal/pull/63464.

Thanks, @jonathanmccann ! :)

**Comment by pedroqueiroz** [comment]
ci:stop

**Pull request closed without merging**
