### PR TITLE
LPS-82653 Replace with http client

### PR DESCRIPTION
**Pull request by marcellustavares**
/cc @topolik

This is a suggestion for a fix for the injection of the parameters.

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Thx @csierra. I'll take a look at this asap.

**Comment by topolik** [comment]
Hi @rafaprax, if you want to fix also SSRF please take a look here: https://github.com/brianchandotcom/liferay-portal/pull/60872/files#diff-9f202f525ed218b41428de8252954c69R397

I'm fixing the same issue somewhere else so feel free to reuse the method. Thanks!

**Comment by rafaprax** [comment]
Ok @topolik . Thx

**Comment by topolik** [comment]
Here it is with tests. Thanks @rafaprax https://github.com/brianchandotcom/liferay-portal/pull/60885

**Comment by rafaprax** [comment]
Pull request forwarded to https://github.com/jeyvison/liferay-portal/pull/179. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
