### PR TITLE
LPS-78362 Update tests to use lexicon display style naming

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
Hey @vicnate5, can you take a look here? Thanks!

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
there was a compile error at head

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
2 problems on this pull
1. Lexicon poshi code is broken in a few places, causes more test failures than normal
2. Need to update the tests for the System Settings configuration change you made

**Comment by vicnate5** [comment]
forwarded https://github.com/rafaprax/liferay-portal/pull/548

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
