### PR TITLE
LPS-78218 Add a common class to the plus button "lfr-ddm-plus-button"

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test

**Comment by alinedoleron** [comment]
Hi @vicnate5, I think @rigosouza has talked with you about the behavior to add a field and add a rule. Just to reinforce:
- To add a new field: click on plus button that has 'lfr-ddm-add-field' class.
- To add a new rule: click on plus button that has 'lfr-ddm-add-rule' class.

**Comment by vicnate5** [comment]
Thanks @alinedoleron. Will take a look

**Comment by vicnate5** [comment]
Forwarded to https://github.com/rafaprax/liferay-portal/pull/373

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
