### PR TITLE
LPS-77345 | master

### PR DESCRIPTION
**Pull request by vicnate5**
@clovisdasilvaneto

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
This looks good. One failure is an unrelated known issue and the other failure looks like a fluke.

**Comment by pedroqueiroz** [comment]
thanks, @vicnate5 !

**Comment by pedroqueiroz** [comment]
LGTM!

**Comment by rafaprax** [comment]
LGTM

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Sent to BChan @ https://github.com/brianchandotcom/liferay-portal/pull/55859.

**Pull request closed without merging**
