### PR TITLE
LPS-000 DO NOT MERGE - only tomcat + db upgrades batches

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
Hey @vicnate5, I did not see the failure in `com.liferay.dynamic.data.mapping.internal.upgrade.v1_1_0.UpgradeCheckboxFieldToCheckboxMultipleField` anymore but the `test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-sybase160-jdk8/2` still failing. I've checked the log and did not find any related issue. So, can you please do a double check here?

Thx

**Comment by vicnate5** [comment]
@rafaprax The test failure is under the `Failures in common with acceptance upstream results` section of the report. Generally that means the failure is unrelated to your changes. It means that the test is failing for everyone.

**Comment by vicnate5** [comment]
@rafaprax Actually the real concern here is that the error in the bug ticket will not be caught here. Gonna send you a custom run.

**Comment by vicnate5** [comment]
https://github.com/rafaprax/liferay-portal/pull/806

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
