### PR TITLE
LPS-71361 Add test

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@rafaprax Tests fixed!

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/47794. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/a0106f9~1...a0106f9) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
