### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test

**Comment by interaminense** [comment]
LGTM.

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
@alinedoleron Real errors here. @rodrigo-e-c-souza Could you take a look at this? Thx

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by vicnate5** [comment]
@pedroqueiroz94 does "Review done" mean I can forward this to BChan after fixing the test?

**Comment by pedroqueiroz94** [comment]
@vicnate5 exactly this! :)

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/54769

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
