### PR TITLE
LPS-80642 remove tab for document library for image field

### PR DESCRIPTION
**Pull request by linolaoj**
cc: @marcelabc

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
LGTM!

**Comment by rafaprax** [comment]
ci:reopen

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/58626. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
