### PR TITLE
LPS-113305 Ensure AssetLink is cleaned of deleted asset entries.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/1041. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/9c784dec15d0~1...9c784dec15d0)

**Pull request closed without merging**
