### PR TITLE
LPS-81793 Add a condition to treat when dataSourceType is equal to from-autofill

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Hey @vicnate5, is it good to go? Thx

**Comment by vicnate5** [comment]
@rafaprax LGTM

**Comment by rafaprax** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/59662. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
