### PR TITLE
LPS-80349 change color for grid required fields

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57914. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/60bc94759a28~1...60bc94759a28) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
hey @vicnate5, do we have a LRQA/LPS for that?

**Comment by vicnate5** [comment]
@pedroqueiroz @rafaprax Needs cross-component fix https://issues.liferay.com/browse/LRQA-40398

Sent here: https://github.com/brianchandotcom/liferay-portal/pull/57936

**Pull request closed without merging**
