### PR TITLE
WIP

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:help

**Comment by rafaprax** [comment]
ci:test:frontend

**Comment by rafaprax** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
@rafaprax @RenanUmV Nao achei regressao. So o erro de semantic.

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:frontend

**Comment by rafaprax** [comment]
ci:test:frontend-ui

**Pull request closed without merging**
