### PR TITLE
LPS-78912 language key

### PR DESCRIPTION
**Pull request by linolaoj**
Please run buildLang.
Thanks!

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
We need to talk to Jadson to see if this is the best approach. I will ping him on Slack. cc @linolaoj

**Comment by pedroqueiroz** [comment]
Resent with build lang at https://github.com/rafaprax/liferay-portal/pull/564.

**Pull request closed without merging**
