### PR TITLE
LPS-81687

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/63627

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63701. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/72e3460611e2~3...72e3460611e2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63702. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/090c86d19a33~3...090c86d19a33) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
