### PR TITLE
LPS-77083 | master

### PR DESCRIPTION
**Pull request by vicnate5**
Resend of https://github.com/rafaprax/liferay-portal/pull/349 with test fixes and SF

CC @alinedoleron @pedroqueiroz94 @rodrigo-e-c-souza

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
Needs more test fixes. Will update.

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
@rafaprax Tests are good. There is an SF error, but I cannot reproduce locally, could be unrelated.

**Comment by rafaprax** [comment]
Thx @vicnate5

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55716. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
