### PR TITLE
LPS-101955 Changing Placeholder place of Numeric element from Advanced to Basic sidebar

### PR DESCRIPTION
**Pull request by gabrielibson**
Related issue: https://issues.liferay.com/browse/LPS-101955

### CODE REVIEW

**Comment by gabrielibson** [comment]
ci:relevant

**Comment by gabrielibson** [comment]
ci:testRelevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83534.

**Pull request closed without merging**
