### PR TITLE
Revert "LPS-197353 Making tests context independent"

This reverts commit fa45c4418a6ed3ad9d00a3da8b5891e4ea0f06b8.

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:workflow

**Comment by rafaprax** [comment]
ci:test:workflow

**Comment by vicnate5** [comment]
@rafaprax Regression here.

Steps to Reproduce:
1. Go to Kaleo Forms Admin
2. Add
3. Input Name > Next
4. Choose existing field set > Next
5. Choose "Single Approver" workflow > Next

Expected Result:
Form list renders.

Actual Result:
Form list/builder does not render.

[ERROR](https://gist.githubusercontent.com/vicnate5/9f9a84acd8b588e1488a47de41ce229c/raw/d79d4bcbff96990cf955fb98ac61d17998222624/gistfile1.txt)

**Comment by rafaprax** [comment]
ci:test:workflow

**Comment by rafaprax** [comment]
Hey @vicnate5, I fixed the issue
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@rafaprax Deeper issue here in Kaleo Forms Admin. Caught by 1 test.
https://testray.liferay.com/home/-/testray/case_results/2452352199

Steps to Reproduce:

1. Go to Kaleo Forms Admin
1. Add
1. Input Name > Next
1. Choose existing field set > Next
1. Click "Add Workflow" button
1. Input a title
1. Go to "Source" tab
1. Upload [workflow definition xml file ](https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/dependencies/1-workflow-definition.xml)
1. Publish
1. Go to "Edit" the workflow definition that was uploaded

Expected Result:
Workflow builder UI renders with all nodes

Actual Result:
Workflow builder UI does not render with all nodes. Error is thrown that the definition is invalid. Sometimes on re-navigation to edit the definitions, the UI fails to load fully.

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:workflow

**Comment by rafaprax** [comment]
I broke down the "WIP" commit and sent a final version of this pr here, https://github.com/rafaprax/liferay-portal/pull/1332.

**Pull request closed without merging**
