### PR TITLE
LPS-79651 Remove index IX_103D6207 on JournalArticleImage

### PR DESCRIPTION
**Pull request by inacionery**
Hey @rafaprax,

Could you please take a look at this?

Please see the @achaparro [comments](https://issues.liferay.com/browse/LPS-79651?focusedCommentId=1289412&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1289412).

Thx!

### CODE REVIEW

**Comment by inacionery** [comment]
ci:test

**Comment by NorbertKocsis** [comment]
Hi!

Could you please take a look at this? It's kind of urgent for us.

Thanks!
Norbert

**Comment by rafaprax** [comment]
Hi @NorbertKocsis,

Did you take a look on  @achaparro's [comment](https://issues.liferay.com/browse/LPS-79651?focusedCommentId=1289412&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1289412)?

Thx

**Comment by NorbertKocsis** [comment]
Hi,

I'm not familiar with how we handle JournalArticleImages so I'm really not the person who could tell if dropping that index could cause any problems. That's why I asked help in the first place on LPS-62881 which caused the issue. And @inacionery told me to we can drop the index, so I dropped it :)

Anyway I'm not a big fan of the cleaning as those records seem valid to me (but again I'm not an expert) so I think we should solve the issue instead.

Br,
Norbert

**Comment by inacionery** [comment]
Hi Nobert,

I didn't say you could drop the index. The index I removed was the composition of the image name, please [see](https://github.com/liferay/liferay-portal/commit/2ae96395f2ffbe94e22d3ae63679fadec8d09c25#diff-9fa04ee5aef4fcea348d66590c449fa6L6287).

I'm not an expert in the Journal, maybe the WCM guys could help you better, but from what I've seen in the code this index can not be droped since it's used in a Finder, please [see](https://github.com/liferay/liferay-portal-ee/blob/ee-7.0.x/modules/apps/web-experience/journal/journal-service/service.xml#L272) and this Finder is used in multiple places, please [see](https://github.com/liferay/liferay-portal-ee/blob/7.0.x/modules/apps/web-experience/journal/journal-service/src/main/java/com/liferay/journal/service/impl/JournalArticleImageLocalServiceImpl.java).

Thanks!

**Pull request closed without merging**
