### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
cc. @MichaelPrigge

**Comment by pedroqueiroz** [comment]
ci:retest

**Comment by rafaprax** [comment]
@pedroqueiroz Could you please rebase and resend? Thx

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
I'll rebase and resend

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/pedroqueiroz/liferay-portal/pull/112. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/5983125ad46f~1...5983125ad46f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
