### PR TITLE
LPS-81584 | master

### PR DESCRIPTION
**Pull request by vicnate5**
https://github.com/rafaprax/liferay-portal/pull/752 @alinedoleron

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60922. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/c76438ca605a~1...c76438ca605a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
