### PR TITLE
LPS-59291

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/31780

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/marcellustavares/liferay-portal/pull/898. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/489417a~1...489417a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/32087. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/ab50dba~1...ab50dba) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/32471. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/ce87bc7~2...ce87bc7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
