### PR TITLE
[TECHNICAL-SUPPORT] LPS-86565

### PR DESCRIPTION
**Pull request by JosemariaMunoz**
https://issues.liferay.com/browse/LPS-86565

Hi @rafaprax !,

I send you this PR instead of that one: https://github.com/pedroqueiroz/liferay-portal/pull/189 that I was already talking with @pedroqueiroz about it. Please ask me any doubt that you could have.

Summarizing last PR, there were some tests that didn't work and I was researching why, because there was something weird for me. 

After some researching (and after change my PR) now  those tests are working fine and I know why didn't work before. If you see [current code](https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/internal/render/BaseNumberDDMFormFieldValueRenderer.java#L39-L43) (before my PR), decimal value needs to be in en_US format (or any language with a period (.) as decimal separator), even when users are using a different language than en_US, for example pt_BR. For example, I show you one use case:
- Default portal language is en_US.
- User administrator create a DDL with a field as decimal value with 2 available languages: en_US and pt_BR.
- A user add 1,2 as a decimal value in that ddl and in pt_BR (language for the ddl form, not portal language).
- In Data Base we are saving next values:
`{"en_US":"","pt_BR":"1,2"}`
So, when you try to see DDL records in widget Dynamic Data Lists Display in pt_BR (this time portal language), value will be 0 (zero), because in [this code](https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/internal/render/BaseNumberDDMFormFieldValueRenderer.java#L39-L43) _valueString_ will be _1,2_ and result for '_GetterUtil.getNumber(valueString);_' will be 0.

Regarding test [testDecimalFieldValueRenderer](https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-test/src/test/java/com/liferay/dynamic/data/mapping/render/DDMFormFieldValueRendererTest.java#L166-L182) (which failed in last PR) is the same that we update to Data Base next values:
`{"en_US":"1.2","pt_BR":"1.2"}`
You will obtain 1,2 when you portal language is pt_BR but we need to have in mind that user will not add 1.2 in pt_BR, user will try to add 1,2 (because decimal value is 1,2 in pt_BR). So, I think we need other real use case, Don't you think like that?

So I created a closer real use case in [_testDecimalFieldValueRendererWithoutDefaultValue_](https://github.com/rafaprax/liferay-portal/pull/913/files#diff-a0e5d535285ff6193300fe6a05f790ceR185), where Data Base should have next values:
`{"en_US":"","pt_BR":"1,2"}`

Does all of this make sense to you? 

The [commit](https://github.com/rafaprax/liferay-portal/pull/913/commits/51cec5b89662f3224714e531fa7cf77a010a0625) which resolve this situation just check if _valueString_ (the right value for the language) is the same that formatted 'number', if not, it is because a parse of this value is needed due to it is in a different language. I think is a better solution because I tried to don't affect rest of code, minimizing number of possible issues.

Please tell me any doubt you have and change (or ask me to change) whatever you think should be changed.

Thanks a lot!

### CODE REVIEW

**Comment by JosemariaMunoz** [comment]
ci:test

**Comment by JosemariaMunoz** [comment]
ci:reopen

**Comment by JosemariaMunoz** [comment]
Other question that I forgot @rafaprax ,
I think this solution only applies to decimal fields so, maybe it is better if we use _DecimalDDMFormFieldValueRenderer_ instead of _BaseNumberDDMFormFieldValueRenderer_, don't you think?
Thanks a lot!

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/64944. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/4b3a0ea37c79~1...4b3a0ea37c79) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
