### PR TITLE
LPS-72435 Extract logic to a method and apply it

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@rafaprax Phil wrote some test fixes, can I resend this so we merge the fixes together with the code change?

**Comment by pedroqueiroz** [comment]
Please, @vicnate5, go ahead! :)

**Comment by vicnate5** [comment]
Forwarded to run the tests: https://github.com/vicnate5/liferay-portal/pull/951
 
Then I will send this in, since the review is done

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
