### PR TITLE
LPS-70431 Avoid rendering when ddmFormFieldValue has null values

### PR DESCRIPTION
**Pull request by marcellustavares**
@rafaprax please create a unit test for this bug. Thanks

cc @SpencerWoo @jonathanmccann

### CODE REVIEW

**Comment by rafaprax** [comment]
Hey @SpencerWoo Could you please resend this to ddm repo? Thx

**Comment by SpencerWoo** [comment]
Resent via https://github.com/rafaprax/com-liferay-dynamic-data-lists/pull/1

**Comment by rafaprax** [comment]
@SpencerWoo I'm reopening this because the DDL repo isn't available yet. My mistake I thought this fix belonged to DDM code, sorry. 😞

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/46958. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/e5482f4~2...e5482f4) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/47025. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/6de9dad~2...6de9dad) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
