### PR TITLE
LPS-79187 Remove if condition in _onNameEditorChange method to allow any character quantity when user change form title or description

### PR DESCRIPTION
**Pull request by clovisdasilvaneto**

### CODE REVIEW

**Comment by clovisdasilvaneto** [comment]
ci:test

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56567. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by vicnate5** [comment]
@clovisdasilvaneto This fixes the basic issue with the titles, but all the tests still failing because the user cannot actually submit a Form entry anymore. I am going going to open a new ticket because I do not know if it is related.

**Comment by vicnate5** [comment]
https://issues.liferay.com/browse/LPS-79215

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by rafaprax** [comment]
already merged

**Comment by vicnate5** [comment]
ci:stop

**Pull request closed without merging**
