### PR TITLE
LPS-81615 Add langKey to autoSave tooltip

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
Hey @alinedoleron , there is a real issue there, if you see `FormRules#EditRule`. Can you check that? Thanks!

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
sent to https://github.com/rafaprax/liferay-portal/pull/730

**Pull request closed without merging**
