### PR TITLE
LPS-102601 log the errors

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Hey @robertoDiaz real errors here. Can you please take a look and resend? Thx

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
Hey @rafaprax 

This PR just introduces some logs in the exceptions.

How could this break tests?

Thanks!

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/972. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Hey @robertoDiaz,

the issue is the our tests expected a clean log and now after your changes it is no more valid. So, you need to update the tests to fix it.

Thx

**Pull request closed without merging**
