### PR TITLE
LPS-57536 Add tests to cover permission filter query and search methods

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by marcellustavares** [comment]
@rafaprax, do you have an update of this issue? Thanks

**Comment by rafaprax** [comment]
@marcellustavares, I'll finish it today.

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Pull request closed without merging**
