### PR TITLE
LPS-87020 JS error when trying to add translations to Web Content fields

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @marianoalvarosaiz, @crodriguezy, @p2kmgcl

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
Pull request forwarded to https://github.com/jeyvison/liferay-portal/pull/144. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
