### PR TITLE
LPS-66882 Add test

### PR DESCRIPTION
**Pull request by marcellustavares**
@rafaprax, could you please double check this test case?

Thanks

---
This change is [Reviewable](https://reviewable.io/reviews/rafaprax/liferay-portal/104)

### CODE REVIEW

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Hey @mbowerman Could you please resend this to ddm repo? Thx

**Comment by mbowerman** [comment]
Hi @rafaprax Please see https://github.com/rafaprax/com-liferay-dynamic-data-mapping/pull/2

**Comment by rafaprax** [comment]
Thx @mbowerman

**Pull request closed without merging**
