### PR TITLE
LPS-81314 button position

### PR DESCRIPTION
**Pull request by linolaoj**
cc: @andreldm

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
LGTM

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
sento to https://github.com/brianchandotcom/liferay-portal/pull/58911

**Pull request closed without merging**
