### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
ci:retest

**Comment by pedroqueiroz** [comment]
@vicnate5 , are these test failures related to the PR?

**Comment by pedroqueiroz** [comment]
This PR is covered by Unit tests.

**Comment by vicnate5** [comment]
@pedroqueiroz Not related. This is good.

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56387. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/1199a5eaa4f1~1...1199a5eaa4f1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
