### PR TITLE
LPS-80303 Destroy portlet

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
@alinedoleron These commits are included in other pr, see https://github.com/rafaprax/liferay-portal/pull/585.

//cc @pedroqueiroz

**Comment by alinedoleron** [comment]
Hi @rafaprax, I removed them now.

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
@vicnate5, the alert markup has changed. Can you take look on that? Thanks!

**Comment by vicnate5** [comment]
@pedroqueiroz @alinedoleron The markup remains the same, but the message is completely removed from the HTML. This causes a problem for testing, because of the time limit on the message. If the test moves too slow, it will miss the message. This will cause flakiness in our tests. Other success messages in portal will remain in the HTML, but will be hidden. This makes it easy for our tests to account for the message whether it has timed out or not. Is there a reason this message is behaving differently than other messages in portal?

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:stop

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@alinedoleron I don't know if you want to fix here, but there is a regression cause by the previously merged commits for LPS-80303. See https://issues.liferay.com/browse/LPS-80744

**Pull request closed without merging**
