### PR TITLE
LPS-98525 SF

### PR DESCRIPTION
**Pull request by rafaprax**
Hey @brianikim,

just waiting for ci results here, after that I gonna forward this to BChan. Just a question, did you do some performance tests to check the improvement of the performance?

Thx

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by brianikim** [comment]
Hello @rafaprax ,

I did some performance tests, but of course I do understand that my testing may have not been thorough. There were slight improvements due to the one less transaction we are doing in the update with the proposed changes (add or update) vs. always doing at least two transactions (delete, then add, or delete, then update). If you can think of any additional performance tests I should be doing, please let me know.

Sincerely,
Brian Kim

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76416. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/c84f4a1b9c3a~1...c84f4a1b9c3a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
