### PR TITLE
[Component with its own class name as service type] LPS-200284 Remove own class as service for some commerce-product-content-web classes

### PR DESCRIPTION
**Pull request by rcsdnj**
CPDefinitionLinkInfoItemRenderer, PriceInfoItemRenderer.java and ProductCardInfoItemRenderer were refering to their own class as an implemented service, as [pointed here](https://docs.google.com/spreadsheets/d/1y-4j4IYr7LDKDVXoOFIFvqyYgTb5t0w-iDxyyEw5OJw/edit?usp=sharing).

### CODE REVIEW

**Comment by rcsdnj** [comment]
ci:test:sf

**Comment by rcsdnj** [comment]
ci:test:help

**Comment by rcsdnj** [comment]
ci:help

**Comment by rcsdnj** [comment]
ci:test:commerce

**Comment by rafaprax** [comment]
Already sent to core-infra repo

**Pull request closed without merging**
