### PR TITLE
LPS-83993 Avoid NPE

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test:sf

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
ci:test:sf

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
Hey @vicnate5, I don't think `Forms#SubmitWithRequiredDateField ` is related.

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by vicnate5** [comment]
@pedroqueiroz Yea, I modified this test to have more coverage and there is a bug with the date field (LPS-84020). Unrelated to your changes here.

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/61837. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
