### PR TITLE
LPS-77158

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hey @rafaprax, 

Please review this PR. Basically we are facing 2 issues where localizationMap is messed up:

1. Clicking quickly in translation manager before the editor is ready.
2. Changing among languages in translation manager.

That's the reason why the event that disable/enable the chance to click on TranslationManager is fired every time we change language.

This issue is reproducible with any editor, that's the reason why the event is triggered from all of them.

Anyway, You can find further information in LPS-77158 or just ask me (or @NemethNorbert)

Thanks.

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Hey guys, after these changes I'm not able ta add translations on Web Content. Can you take a look and fix that?

Thx

**Comment by NemethNorbert** [comment]
@antonio-ortega  @rafaprax 
Looking into it.
Thx

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/jbalsas/liferay-portal/pull/1015. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/c77c5a324aac~2...c77c5a324aac) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
