### PR TITLE
[TECHNICAL-SUPPORT] LPS-78710

### PR DESCRIPTION
**Pull request by jonathanmccann**
@rafaprax Not sure if this is your area or not. If not, please let me know who to forward DDM issues to.

/cc @gregory-bretall

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by rafaprax** [comment]
Hey @jonathanmccann , DDM is my area. Bugs related to DDM you can send to @pedroqueiroz or me. Thx

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jonathanmccann** [comment]
Thanks for confirming @rafaprax

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56561. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
