### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by pedroqueiroz94**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
@rodrigo-e-c-souza Could you please check this pr? The errors seem related to @marcelabc changes. Thx

**Comment by rodrigo-e-c-souza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rodrigo-e-c-souza** [comment]
ci:test

**Comment by vicnate5** [comment]
@alinedoleron @pedroqueiroz94 @rodrigo-e-c-souza The reason for the test failures here is because the Checkbox and Radio field inputs are now "not visible" elements and are covered up by the `<span>` labels (`custom-control-label`). This affects the testability because the test can only click on the **span**, and not the checkbox or radio **input**.

```
Element is not clickable at point... Other element would receive the click: <span class="form-check-description custom-control-label"></span>
```

Would it be possible to adjust the input element to be easier to access?

**Comment by vicnate5** [comment]
Resent https://github.com/rafaprax/liferay-portal/pull/362

**Comment by vicnate5** [comment]
ci:close

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
