### PR TITLE
LPS-183802 Baseline

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@rafaprax No regressions found.

**Comment by rafaprax** [comment]
forwarded manually to BChan here https://github.com/brianchandotcom/liferay-portal/pull/134683

**Comment by rafaprax** [comment]
forwarded manually to BChan here https://github.com/brianchandotcom/liferay-portal/pull/134683

**Comment by rafaprax** [comment]
forwarded manually to BChan here https://github.com/brianchandotcom/liferay-portal/pull/134683

**Pull request closed without merging**
