### PR TITLE
[TECHNICAL-SUPPORT] LPS-82059

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @joshuacords

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:test:reopen

**Comment by joshuacords** [comment]
ci:stop

**Comment by joshuacords** [comment]
ci:reopen

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Sent to BChan at https://github.com/brianchandotcom/liferay-portal/pull/60245.

**Pull request closed without merging**
