### PR TITLE
LPS-58580 SF

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
@rafaprax there's a compilation issue, could you please take care of it? Thanks

**Comment by rafaprax** [comment]
Ok @marcellustavares

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/marcellustavares/liferay-portal/pull/803. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/5207b01~4...5207b01) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
