### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
Hey @vicnate5 , can you take a look at this?

Differently from https://github.com/rafaprax/liferay-portal/pull/364, now the * is being rendered, but the text still fails. Thanks!

**Comment by vicnate5** [comment]
@pedroqueiroz Will check.

**Comment by vicnate5** [comment]
Forwarded to https://github.com/rafaprax/liferay-portal/pull/383 with test fix.

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
