### PR TITLE
LPS-77232 User clay:navigation-bar instead of the old aui:navbar tag

### PR DESCRIPTION
**Pull request by pedroqueiroz94**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:reopen

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/55185. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
