### PR TITLE
LPS-122477 Fix redirect after assigning workflow task to self

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-122477

The issue was the page was not redirecting to the Assigned to Me tab after assigning a workflow task to self.
I fixed this issue by changing the redirect value in workflow_task_action.jsp from currentURL to redirectURL.toString().
UPDATE: I added a condition whether Assign To Me is accessed from the tasks list or from inside the task.

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/liferay-workflow/liferay-portal/pull/101. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/e92e72062c62~1...e92e72062c62)

**Pull request closed without merging**
