### PR TITLE
LPS-82324 Remove old versions in KaleoDefinition

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:reopen

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/766. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/93a546e83b30~2...93a546e83b30) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
