### PR TITLE
LPS-76558 Auto SF

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/570. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/d49e65c65327~1...d49e65c65327) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
