### PR TITLE
LPS-79494 | master

### PR DESCRIPTION
**Pull request by vicnate5**
@pedroqueiroz @alinedoleron

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rodrigopaulino** [comment]
Hey, @alinedoleron.

After deploying these commits, I was able to detect a regression: once I put a number on the validation field, I wasn't able to change it again, unless I disable the validation and enable it again. Could you please check that?
Here's the behavior before the commits:
before

Here's after:
after

Regards.

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
I sent a new PR with the fix. https://github.com/rafaprax/liferay-portal/pull/589

**Pull request closed without merging**
