### PR TITLE
LPS-77095 | master

### PR DESCRIPTION
**Pull request by vicnate5**
@pedroqueiroz

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:reopen

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Resent at https://github.com/rafaprax/liferay-portal/pull/385.

**Comment by pedroqueiroz** [comment]
Thanks for the test fixes, @vicnate5 :)

**Pull request closed without merging**
