### PR TITLE
LPS-79445 Set validation to numeric to avoid the conversion to number in the evaluator process

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
Hey @vicnate5, can we cover this with poshi test? Thanks!

**Comment by vicnate5** [comment]
https://issues.liferay.com/browse/LRQA-40422

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Fixed unit test and sent to BChan: https://github.com/brianchandotcom/liferay-portal/pull/57719

**Pull request closed without merging**
