### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests tomcat 9

### PR DESCRIPTION
**Pull request by linolaoj**
Please run buildLang.

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:reopen

**Comment by linolaoj** [comment]
ci:retest

**Comment by pedroqueiroz** [comment]
LGTM. Waiting tests results and need to build lang.

**Comment by pedroqueiroz** [comment]
ci:stop

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Sent to BChan at https://github.com/brianchandotcom/liferay-portal/pull/57425.

**Pull request closed without merging**
