### PR TITLE
[Component with its own class name as service type] LPS-198805 Refactor Controller components part I

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-198805

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:analytics-cloud-acceptance

**Comment by MrJohn1911** [comment]
ci:test:analytics-cloud-acceptance

**Review by rafaprax — APPROVED** [review]

**Comment by rafaprax** [comment]
send to core-infra repo

**Pull request closed without merging**
