### PR TITLE
[Components with more than 1 service] LPS-184314 Refactor Miscellaneous components from portal-search-elasticsearch7 module

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:search

**Comment by MrJohn1911** [comment]
@rafaprax Please see this [comment](https://github.com/brianchandotcom/liferay-portal/pull/136875#issuecomment-1606738004), thx.

**Comment by rafaprax** [comment]
forwarded manually to BChan here https://github.com/brianchandotcom/liferay-portal/pull/136975

**Pull request closed without merging**
