### PR TITLE
LPS-73721 Use the default duplication title  when user doesnt inform it

### PR DESCRIPTION
**Pull request by jeyvison**
Hey @rafaprax , the CI tests are running in [this pull](https://github.com/jeyvison/liferay-portal/pull/22).

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
@jeyvison , can you please rebase? Thanks!

**Comment by jeyvison** [comment]
@pedroqueiroz rebased :)

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55926. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/04e060945c29~1...04e060945c29) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
