### PR TITLE
LPS-80819 Add margin to Required field info message

### PR DESCRIPTION
**Pull request by andreldm**

### CODE REVIEW

**Comment by andreldm** [comment]
ci:test:relevant

**Comment by andreldm** [comment]
ci:reopen

**Comment by andreldm** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Hey @andreldm , now the message is positioned far to the right. I think it should be aligned according to the fields. Please fix it. 

Thx

screen shot 2018-05-16 at 10 45 58 am

**Pull request closed without merging**
