### PR TITLE
LPS-66844 | master

### PR DESCRIPTION
**Pull request by vicnate5**
Hey @rafaprax, Adam sent me this pull but saving forms seems to be broken. Could you take a look? This also needs poshi fixes so you can send back to me when you are done. Thanks

### CODE REVIEW

**Comment by rafaprax** [comment]
Hey @vicnate5 I'll take a look. Thx

**Comment by rafaprax** [comment]
ci:reopen

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
ci:retest

**Comment by marcellustavares** [comment]
@rafaprax, could you please send this to me after you finish? I still have some concerns about this.

**Comment by rafaprax** [comment]
Sure @marcellustavares

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/163. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/dd372cc~6...dd372cc) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/165. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/e4818ff~6...e4818ff) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
