### PR TITLE
LPS-83993 Avoid NPE

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test:sf

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Hey @pedroqueiroz, there are some regressions here. Can you please fix and resend? Thx

PS: I tried to find out and fix the problem, but I could not. Sorry :(

**Pull request closed without merging**
