### PR TITLE
LPS-82171 Update tests

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test:sf

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@pedroqueiroz @rafaprax I tested the Permissions fix. It is mostly working, `Forms > Access in Site Administration` is the only one that doesn't get brought over on upgrade.

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Hey @vicnate5,

I tested here and the `Forms > Access in Site Administration` is showing up to me at the define permissions tab from `Form Builder` Role. 

screen shot 2018-07-06 at 11 13 11 am

Thx

//cc @pedroqueiroz

**Comment by vicnate5** [comment]
Hmm. I am using the same dump but still cannot see that permission. I built this pull locally.

screenshot 2018-07-06 09 30 54

Using mysql 5.7.17
[Full upgrade log](https://gist.github.com/vicnate5/4818c98a5a704992b51765284141a9fe)

I am disabling indexing during upgrade, setting back to false after the upgrade.
`echo "indexReadOnly=true" > ./osgi/configs/com.liferay.portal.search.configuration.IndexStatusManagerConfiguration.cfg`

My portal-ext
```
plugin.notifications.enabled=false
jdbc.default.jndi.name=
jdbc.default.driverClassName=com.mysql.jdbc.Driver
jdbc.default.url=jdbc:mysql://localhost:3306/lportal7?characterEncoding=UTF-8&dontTrackOpenResources=true&holdResultsOpenOverStatementClose=true&useFastDateParsing=false&useUnicode=true
jdbc.default.username=
jdbc.default.password=
browser.launcher.url=
index.on.startup=true
setup.wizard.enabled=false
mail.session.jndi.name=
sprite.root.dir=/tmp/sprite
memory.scheduler.org.quartz.threadPool.threadCount=1
persisted.scheduler.org.quartz.threadPool.threadCount=1
virtual.hosts.default.site.name=
module.framework.properties.blacklist.portal.profile.names=com.liferay.chat.service,com.liferay.chat.web,opensocial-portlet
module.framework.properties.osgi.console=11312
```

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
I will take a look on that.

**Pull request closed without merging**
