### PR TITLE
LPS-78362 | master

### PR DESCRIPTION
**Pull request by vicnate5**
Fixes for https://github.com/rafaprax/liferay-portal/pull/541

@pedroqueiroz this should be good now. There are some unique poshi failures, but they need to be fixed outside the scope of this pull because it affects all components that use the new lexicon patterns.

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
LGTM

Existing Test failures need to be fixed across portal by https://issues.liferay.com/browse/LRQA-40398 and https://issues.liferay.com/browse/LRQA-40329

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57804. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57810. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/e4c9b7e7b99e~1...e4c9b7e7b99e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
