### PR TITLE
LPS-70097 Update tests

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@rafaprax Please test with my changes and if it's ok you can forward to @ctampoya .

@marcellustavares We created a new issue to deal with calling LocalService from MVCCommand classes.

**Comment by marcellustavares** [comment]
thx @leoadb!

**Comment by leoadb** [comment]
ci:reopen

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/159. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/34ed844~1...34ed844) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/ctampoya/liferay-portal/pull/65. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/34ed844~1...34ed844) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/ctampoya/liferay-portal/pull/66. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/45646f3~1...45646f3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
