### PR TITLE
LPS-81609 Update unit tests

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@rafaprax @jeyvison @pedroqueiroz

**Comment by leoadb** [comment]
@rafaprax @jeyvison @pedroqueiroz I just fixed the rebase issues. We need to merge this, please!! No more rebases :)

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
