### PR TITLE
LPS-99441 | LPS-104874 Apply date range filter on "view all assignees" link

### PR DESCRIPTION
**Pull request by albinojunior**

### CODE REVIEW

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
sent to BChan at https://github.com/brianchandotcom/liferay-portal/pull/81486

**Pull request closed without merging**
