### PR TITLE
LPS-85127 Fix unit tests (java)

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Sento to BChan: https://github.com/brianchandotcom/liferay-portal/pull/62815

**Pull request closed without merging**
