### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:reopen

**Comment by rafaprax** [comment]
ci:test

**Comment by marcelabc** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
LGTM! @rafaprax

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/pedroqueiroz/liferay-portal/pull/140. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/b164180f5ea1~10...b164180f5ea1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
