### PR TITLE
LPS-80362 changing fieldName of copied field according to label

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
LGTM!

**Comment by linolaoj** [comment]
Hi @vicnate5, we changing the name of the copied field. Can you update LocalFile.Forms#AddFormWithDuplicateTextFields if necessary?
Thanks!

**Comment by vicnate5** [comment]
@linolaoj When I fixed the test, I noticed a problem with the label not updating on the Form builder for the duplicate field. This is a change of behavior from head.

unresponsivelabelchange

**Comment by vicnate5** [comment]
Pushed test fix to Lino
https://github.com/linolaoj/liferay-portal/pull/122

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
