### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by clovisdasilvaneto**

### CODE REVIEW

**Comment by clovisdasilvaneto** [comment]
ci:test

**Comment by alinedoleron** [comment]
ci:reopen

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56675. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/f8e28cecc6ac~1...f8e28cecc6ac) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
