### PR TITLE
LPS-78054 language key

### PR DESCRIPTION
**Pull request by linolaoj**
cc/ @pedroqueiroz94

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test

**Comment by pedroqueiroz94** [comment]
ci:test

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by linolaoj** [comment]
@rafaprax , I pushed some changes.

**Comment by pedroqueiroz94** [comment]
LGTM

**Comment by rafaprax** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/55506. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/243c27af3218~2...243c27af3218) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
