### PR TITLE
[TECHNICAL SUPPORT] LPS-107051 DDM structures with translations cannot be saved in case you add a radio or select field

### PR DESCRIPTION
**Pull request by jeyvison**
https://issues.liferay.com/browse/LPS-107051

In order to solve this issue, in case any language is missing, I am getting the text from default one.
In the first commit https://github.com/jeyvison/liferay-portal/pull/669/commits/02d2d5ff99b83da5caac779e9826582acfcca606, I have just copied the code from here:
 - https://github.com/liferay/liferay-portal/blob/9d9fde2b59f8d50feed7ccd01519dbd8edf064a9/modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/js/custom_fields.js#L1177-L1205

As it is the same code in both places, I have extracted it to a new method (see commit https://github.com/jeyvison/liferay-portal/pull/669/commits/a057e125bb959d0ab60b158ec6e029eee945e923) and made some simplifications to it (see commit https://github.com/jeyvison/liferay-portal/pull/669/commits/cde9893f0ed73fa254acfc91540bdde5711d9eaf).

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
Hi @rafaprax 

Did you have the opportunity to review this PR?

Can I send this code change in a hotfix to our customer?

Thank you,
Jorge

**Comment by rafaprax** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83389. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/c8718b46ed6f~1...c8718b46ed6f)

**Comment by jorgediaz-lr** [comment]
Thank you, @rafaprax!

**Comment by rafaprax** [comment]
Thanks for you fix, @jorgediaz-lr!

**Pull request closed without merging**
