### PR TITLE
LPS-79447 | master

### PR DESCRIPTION
**Pull request by vicnate5**
https://github.com/rafaprax/liferay-portal/pull/590

### CODE REVIEW

**Comment by vicnate5** [comment]
@pedroqueiroz

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@pedroqueiroz Forms completely broken?
```
Current URL /group/guest/~/control_panel/manage?p_p_id=com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet&p_p_lifecycle=0&p_p_state=maximized generates exception: java.lang.NullPointerException
javax.portlet.PortletException: javax.servlet.ServletException: com.liferay.dynamic.data.mapping.form.renderer.DDMFormRenderingException: com.liferay.portal.kernel.template.TemplateException: Unable to process templates
```

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Resent at https://github.com/rafaprax/liferay-portal/pull/601. Thanks for catching this, @vicnate5 !

**Pull request closed without merging**
