### PR TITLE
LPS-78694 Close sidebar when start dragging field

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
@vicnate5 , can we cover this behavior in a poshi test?

**Comment by vicnate5** [comment]
Maybe? Would need to see the behavior.

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
Also, no unique failures on this pull

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56526. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
cool, @vicnate5 ! Thanks a lot!

**Pull request closed without merging**
