### PR TITLE
LPS-77352 adjust empty form on page reset

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:reopen

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
LGTM! :)

**Comment by leoadb** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
LGTM!

**Comment by pedroqueiroz94** [comment]
Resent at https://github.com/rafaprax/liferay-portal/pull/328.

**Pull request closed without merging**
