### PR TITLE
LPS-77549 Remove line of Rules action and adjust background color

### PR DESCRIPTION
**Pull request by clovisdasilvaneto**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55133. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
