### PR TITLE
LPS-151342 Use a httpServletRequest to get the pathInfo and the servletContext from the originalServletRequest instead

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Hey @vicnate5,

Can you please confirm that the [test-portal-acceptance-pullrequest-batch(master)/functional-smoke-wildfly180-mariadb104-jdk8/0](https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/47741/) is related to my changes?

Thx

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
@rafaprax This does break non-tomcat app server JSONWS endpoints (Wildfly, Jboss, Weblogic) as well as some JSONWS endpoints on Tomcat.

1. Wildfly/Weblogic cannot get the company ID with `curl -X GET -u 'test@liferay.com:test' http://localhost:8080/api/jsonws/company/get-company-by-virtual-host/virtual-host/localhost`
2. Tomcat missing different endpoints

 dlapp/add-file-entry
```
Executing commands: curl -X POST -u 'test@liferay.com:test' -F 'externalReferenceCode=' -F 'repositoryId=42658' -F 'folderId=0' -F 'sourceFileName=Document_1.jpg' -F 'mimeType=image/jpeg' -F 'title=DM Document Title' -F 'urlTitle=' -F 'description=DM Document Description' -F 'changeLog=' -F 'file=@test/functional/com/liferay/portalweb/dependencies/Document_1.jpg' -F 'serviceContext={"addGroupPermissions" : true, "addGuestPermissions": true}' http://cloud-10-0-110-159.lax.liferay.com:8080/api/jsonws/dlapp/add-file-entry
     [exec] 2022-04-28 02:47:32.536 ERROR [http-nio-8080-exec-7][JSONWebServiceServiceAction:126] No JSON web service action with path /dlapp/add-file-entry and method POST for null
``` 
remoteapp.remoteappentry/add-i-frame-remote-app-entry
```
Executing commands: curl -X POST -u 'test@liferay.com:test' -d 'description=' -d 'friendlyURLMapping=' -d 'iFrameURL=http%3A//www.liferay.com/my_new_remote_app' -d 'instanceable=true' -d 'nameMap='{\"en_US\":\"My%20New%20Remote%20App%20To%20Delete\"}'' -d 'portletCategoryName=RemoteApps' -d 'properties=' -d 'sourceCodeURL=' http://cloud-10-0-10-67.lax.liferay.com:8080/api/jsonws/remoteapp.remoteappentry/add-i-frame-remote-app-entry
     [exec] 2022-04-28 01:25:17.008 ERROR [http-nio-8080-exec-3][JSONWebServiceServiceAction:126] No JSON web service action with path /remoteapp.remoteappentry/add-i-frame-remote-app-entry and method POST for remoteapp
```

mb.mbmessage/add-message-attachment
```
 Executing commands: curl -X POST -u 'test@liferay.com:test' -F 'messageId=61591' -F 'fileName=Document_1.jpg' -F 'mimeType=image/jpeg' -F 'file=@test/functional/com/liferay/portalweb/dependencies/Document_1.jpg' http://test-1-25-74.lax.liferay.com:8080/api/jsonws/mb.mbmessage/add-message-attachment
     [exec] 2022-04-28 01:05:22.622 ERROR [http-nio-8080-exec-1][JSONWebServiceServiceAction:126] No JSON web service action with path /mb.mbmessage/add-message-attachment and method POST for mb
```

**Comment by rafaprax** [comment]
Thanks @vicnate5, I'm on it.

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
@rafaprax Tomcat looking good, still have the issue on the other app servers

This command still fails:
`curl -X GET -u 'test@liferay.com:test' http://localhost:8080/api/jsonws/company/get-company-by-virtual-host/virtual-host/localhost`

How to build Wildfly locally:
1. set `app.server.type=wildfly` in app.server.properties
2. ant -f build-dist.xml unzip-wildfly
3. ant all

Also, Unit test failure in [com.liferay.portal.jsonwebservice.JSONWebServiceTest](https://testray.liferay.com/home/-/testray/case_results/1738045090), also failing other tests in this package.

**Comment by rafaprax** [comment]
Hey @vicnate5, you read my mind and anticipated my questions. Thx man.

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
Wildfly test passed here, gonna trigger the rest of the app server testing now

**Comment by vicnate5** [comment]
ci:test:app-servers

**Comment by vicnate5** [comment]
@rafaprax Looks good now, no issues found on any of the app servers.

**Comment by rafaprax** [comment]
Thx @vicnate5

**Comment by rafaprax** [comment]
forwarded to shuyang here https://github.com/shuyangzhou/liferay-portal/pull/10643

**Pull request closed without merging**
