### PR TITLE
LPS-82466 getting existing value when there is no value for default language

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:reopen

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/60859. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/2e66ed95db90~1...2e66ed95db90) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
