### PR TITLE
[TECHNICAL-SUPPORT] LPS-80849

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @joshuacords

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Hey @alinedoleron Could you please help me with this review? Thx

**Comment by joshuacords** [comment]
Notes:
The probelm was an extra instanceId was being added to the fieldName of fields in a fieldSet (Element Set). This caused their validation to fail because the fieldName did not match the validation name. The instanceId is not necessary because a unique instanceId is already included on the fields by another process.

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Hey @vicnate5 Can you please check if the failure at `LocalFile.Forms_AddElementSetsWithTranslation` is related to this pr?

Thx

**Comment by rafaprax** [comment]
Thanks @vicnate5

Hey @joshuacords Can you please take a look at this regression and resend?

/cc @SamZiemer

Thx guys

**Pull request closed without merging**
