### PR TITLE
Revert "LPS-197353 Making tests context independent"

This reverts commit fa45c4418a6ed3ad9d00a3da8b5891e4ea0f06b8.

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:workflow

**Comment by catarineaguiar** [comment]
@rafaprax no regressions on workflow suite.

only found this compile error on relevant:
```
     [exec] > Task :apps:headless:headless-builder:headless-builder-test:buildCSS NO-SOURCE
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/headless/headless-admin-taxonomy/headless-admin-taxonomy-test/src/testIntegration/java/com/liferay/headless/admin/taxonomy/resource/v1_0/test/TaxonomyVocabularyResourceTest.java:152: error: cannot find symbol
     [exec] 		Assert.assertEquals(totalCount + 1, page.getTotalCount());
     [exec] 		                    ^
     [exec]   symbol:   variable totalCount
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-11/test-1-26/test-portal-acceptance-pullrequest(master)/11861/modules-compile-jdk8/0/1/jenkins-console.txt.gz?authuser=0)

**Comment by rafaprax** [comment]
Hey @catarineaguiar, The above compilation failure is related to the revert commits I added temporarily to run the workflow suite. I added them to get rid of the test issues caused by them so I could verify if my changes would introduce new failures or not.

Thx

**Comment by rafaprax** [comment]
forwarded manually to BChan here https://github.com/brianchandotcom/liferay-portal/pull/143427

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
no regressions on relevant after removing revert commits.

**Pull request closed without merging**
