### PR TITLE
[TECHNICAL-SUPPORT] LPS-87176

### PR DESCRIPTION
**Pull request by SamZiemer**
https://issues.liferay.com/browse/LPS-87176

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65115. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65210. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65211. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/f4071a288504~1...f4071a288504) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
