### PR TITLE
LPS-82963 User will not see translated DDM field labels or tips when changing site language. Use the implicit 'locale' variable instead

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
ci:stop

**Comment by pedroqueiroz** [comment]
Sent to Eudaldo at https://github.com/ealonso/liferay-portal/pull/1851.

**Pull request closed without merging**
