### PR TITLE
LPS-85451 Tests for new Upgrade Processes

### PR DESCRIPTION
**Pull request by rodrigopaulino**

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Hey, @rafaprax, I don't think this failure is related to the fix.
I'll rerun the tests and if you already know this is related, please let me know.

**Comment by rodrigopaulino** [comment]
I went through the test report and it looks like these errors have happened before.
I'll rerun them to make sure that these aren't caused by a flaky CI.

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Pull request forwarded to https://github.com/jeyvison/liferay-portal/pull/161. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
