### PR TITLE
[TS] LPS-78856

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by yuhai** [comment]
Hi @rafaprax 

Thanks for reviewing this. The NPE error occured in the test class. I resent the PR to review. 
Please refer to https://github.com/hhuijser/liferay-portal/pull/3216

Regards,
Hai

**Comment by pedroqueiroz** [comment]
Thanks, @yuhai !

**Comment by rafaprax** [comment]
Thx @yuhai

**Pull request closed without merging**
