### PR TITLE
LPS-83600 Join all Forms labels in a Lang module

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
ci:test:sf

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
Hey @vicnate5, is this good to go? Thanks!

**Comment by vicnate5** [comment]
@pedroqueiroz It doesn't look like a regression on `LocalFile.Forms#AddElementSetsWithTranslation`. This is a test issue I have seen before. I can look into it more this week.

**Comment by pedroqueiroz** [comment]
Thanks @vicnate5! 

Sent to BChan at https://github.com/brianchandotcom/liferay-portal/pull/61758.

**Pull request closed without merging**
