### PR TITLE
LPS-79431 Build lang

### PR DESCRIPTION
**Pull request by renatodepaiva**

### CODE REVIEW

**Comment by renatodepaiva** [comment]
ci:test:sf

**Comment by renatodepaiva** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/64493. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/a865cb6ccb45~1...a865cb6ccb45) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/64494. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/a865cb6ccb45~1...a865cb6ccb45) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/64497. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/e3eb50026505~2...e3eb50026505) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
