### PR TITLE
[Components with more than 1 service] LPS-201309 Refactor SXPParameterDataCreator component

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-201309](https://liferay.atlassian.net/browse/LPS-201309)

Previous Pull: https://github.com/rafaprax/liferay-portal/pull/1344

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
Hey @RenanUmV, I think you forgot to run the `gw baseline` here. Please check that and add the missing baseline changes. Th

**Comment by rafaprax** [comment]
forwarded to https://github.com/liferay-core-infra/liferay-portal/pull/6289

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
forwarded to

**Comment by rafaprax** [comment]
forwarded to https://github.com/liferay-core-infra/liferay-portal/pull/6292

**Comment by rafaprax** [comment]
forwarded to

**Pull request closed without merging**
