### PR TITLE
LPS-82378 Change value type to any

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
LGTM!

**Comment by alinedoleron** [comment]
sent to https://github.com/brianchandotcom/liferay-portal/pull/60287

**Pull request closed without merging**
