### PR TITLE
LPS-87084 Form portlet form selector does not see unstaged forms

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @rafaprax 

Could you please review this pull request?
I fixed the tests that failed in https://github.com/rafaprax/liferay-portal/pull/917

Thank you and best regards,
István

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:staging

**Comment by IstvanD** [comment]
Hey @rafaprax 

I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by rafaprax** [comment]
Pull request forwarded to https://github.com/jeyvison/liferay-portal/pull/146. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
