### PR TITLE
LPS-84005 | master

### PR DESCRIPTION
**Pull request by vicnate5**
@pedroqueiroz The remote test I had to ignore. There is an issue with the remote staging enable on the integration tests. The issue also affects all the existing remote staging tests. I reached out to the Staging team about this.

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:reopen

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Hey @vicnate5 , thanks for the PR!

It looks good to me, so I sent to BChan here: https://github.com/brianchandotcom/liferay-portal/pull/62146.

Just did a small SF, like removing unused variables and removing a deprecated Util class.

**Pull request closed without merging**
