### PR TITLE
LPS-77233 User clay:navigation-bar instead of the old aui:navbar tag

### PR DESCRIPTION
**Pull request by pedroqueiroz94**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
ci:test

**Comment by pedroqueiroz94** [comment]
@rodrigo-e-c-souza, can you fix the paths for this PR?

**Comment by rodrigo-e-c-souza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rodrigo-e-c-souza** [comment]
@pedroqueiroz94 fixed those paths on https://github.com/rafaprax/liferay-portal/pull/304

**Comment by rodrigo-e-c-souza** [comment]
ci:close

**Pull request closed without merging**
