### PR TITLE
LPS-77622 Change query

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test

**Comment by alinedoleron** [comment]
ci:reopen

**Comment by alinedoleron** [comment]
@rafaprax, what can I do to solve this problem?

**Comment by rafaprax** [comment]
@alinedoleron We can just waiting for the sf fix :( . Probably the QA guys already notified someone to take a look on that issue.

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55443. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
