### PR TITLE
LPS-81647 Update unit test

### PR DESCRIPTION
**Pull request by andreldm**

### CODE REVIEW

**Comment by andreldm** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Sent to BChan at https://github.com/brianchandotcom/liferay-portal/pull/59838.

**Pull request closed without merging**
