### PR TITLE
[TECHNICAL-SUPPORT] LPS-79235

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @brianikim

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by jonathanmccann** [comment]
@rafaprax The fix changes the URL to lead you to viewing the entires, which @brianikim thought would be a nice way to maintain some functionality. The other option I thought of was to not include the href whatsoever if the user does not have permission. Let us know what you think about the solution.

**Comment by brianikim** [comment]
ci:reopen

**Comment by brianikim** [comment]
ci:retest

**Comment by rafaprax** [comment]
@jonathanmccann @brianikim  Hi guys, after talk with the team, we decided that not include the href whatsoever if the user does not have permission is the correct approach.

@brianikim Can you send another pr fixing that?

Thx

**Comment by brianikim** [comment]
@rafaprax 

Thank you for the insight. I will send the pr with the fix  as you recommended.

**Pull request closed without merging**
