### PR TITLE
LPS-172505 Remove "immediate = true" from remaining Data Integration modules

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:data-integration

**Comment by rafaprax** [comment]
LGTM

**Comment by rafaprax** [comment]
Hey @MrJohn1911, please send it to the core-infra repo. Thx

**Pull request closed without merging**
