### PR TITLE
LPS-80952 | master

### PR DESCRIPTION
**Pull request by vicnate5**
Test fix for https://github.com/rafaprax/liferay-portal/pull/677

@pedroqueiroz @marcelabc

### CODE REVIEW

**Comment by vicnate5** [comment]
force pushed to fix merge conflict

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Resent with extra commits at https://github.com/rafaprax/liferay-portal/pull/702.

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/inacionery/liferay-portal/pull/706.

**Pull request closed without merging**
