### PR TITLE
LPS-77063 Auto SF

### PR DESCRIPTION
**Pull request by pedroqueiroz94**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
ci:test

**Comment by rodrigo-e-c-souza** [comment]
Hi @pedroqueiroz94,

any updates here?

Thanks

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
resent to https://github.com/rafaprax/liferay-portal/pull/360

**Pull request closed without merging**
