### PR TITLE
LPS-100463 Getting PortletURL from the same context. As a fallback we'll keep Control Panel URL

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hi @rafaprax ,

Can you review this pull request, please?

You have further information in LPS-100463, but don't hesitate to ask me anything else you need.

Thanks.

Regards.

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
Hi @rafaprax ,

Can you have a look at this PR, please?

Thanks.

Regards.

**Comment by antonio-ortega** [comment]
Hi @inacionery ,

Should I send this pull request to you?

Thanks!

**Comment by inacionery** [comment]
Hi @antonio-ortega,

You can send it to me, but I'm not understanding the fix, `PortletURLFactoryUtil.create` is returning null? Because as far as I know, it should not return null. I don't have access to the Zendesk ticket, could you please tell me exactly what the customer's complaint is? Once the Workflow Task Portlet is a portlet of Control Panel, it should be opened with the theme and URL of the Control Panel.

Thanks!

**Comment by antonio-ortega** [comment]
inacionery#213

**Pull request closed without merging**
