### PR TITLE
LPS-57957 Update liferay workflow definition xsd to correctly validate scripted assignemnt.

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by daviddotzhang** [comment]
@rafaprax 

As this is a customer issue, it ?could you kindly set a high priority to review it?

thanks in advance

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/inacionery/liferay-portal/pull/28. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
