### PR TITLE
LPS-75462 Fix unit test

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/387. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/93e0f5ddd58d~1...93e0f5ddd58d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
