### PR TITLE
LPS-120371 SF

### PR DESCRIPTION
**Pull request by albinojunior**
cc: @gabrielpramos

### CODE REVIEW

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/liferay-workflow/liferay-portal/pull/2. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/b6be962162db~1...b6be962162db)

**Pull request closed without merging**
