### PR TITLE
LPS-78618 Move search field to management bar

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
@rafaprax , tests not needed because we don't have JS Unit tests.

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56180. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
