### PR TITLE
LRQA-37132 Ignoring the test for further analysis

### PR DESCRIPTION
**Pull request by pedroqueiroz94**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
ci:test

**Comment by rafaprax** [comment]
LGTM

**Comment by rodrigo-e-c-souza** [comment]
ci:stop

**Comment by rodrigo-e-c-souza** [comment]
Resent at https://github.com/rafaprax/liferay-portal/pull/316.

**Comment by rodrigo-e-c-souza** [comment]
ci:close

**Pull request closed without merging**
