### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by rafaprax** [comment]
Hey @vicnate5 Could you please check if these test failures are related to @alinedoleron's changes? Thx

**Comment by vicnate5** [comment]
@rafaprax Failures are not related.

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56147. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
