### PR TITLE
LPS-78136 model resource permission has to be declared on service class

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test

**Comment by linolaoj** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55693. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/a208ceb5b77c~5...a208ceb5b77c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55713. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/88679272f343~5...88679272f343) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
