### PR TITLE
LPS-79335 translation and delete button position

### PR DESCRIPTION
**Pull request by linolaoj**
cc: @andreldm, @alinedoleron , @rodrigopaulino

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
LGTM

**Comment by alinedoleron** [comment]
sent to https://github.com/brianchandotcom/liferay-portal/pull/58460

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/58628. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/51eab0516f81~1...51eab0516f81) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
