### PR TITLE
LPS-70813 buildLang

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:retest

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/leoadb/liferay-portal/pull/317. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/ab7bc20~1...ab7bc20) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/47582. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/ec8734e~1...ec8734e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/47599. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/6495e2a2~5...6495e2a2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/47637. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/e479f44~5...e479f44) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
