### PR TITLE
LPD-17407 Set CLDR as the default locale provider

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:help

**Comment by rafaprax** [comment]
ci:report:2536854686

**Comment by julschong** [comment]
ci:test:upstream-functional

**Comment by julschong** [comment]
@rafaprax I'm running all functional tests with CLDR to compare with jdk17 all functional tests results

**Comment by julschong** [comment]
ci:report:2539607501

**Comment by julschong** [comment]
ci:report:2539607501

**Comment by julschong** [comment]
ci:report:2539607501

**Comment by julschong** [comment]
ci:test:upstream-functional

**Comment by rafaprax** [comment]
resent here https://github.com/rafaprax/liferay-portal/pull/1430

**Pull request closed without merging**
