### PR TITLE
Lps 106224

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @knchau

Notes from Kim:
> https://issues.liferay.com/browse/LPS-106224
> 
> **Issue:**
> In the Calendar Widget, when in the 'Month' view if you click on a day and add an event then uncheck "All Day", the default starting time of the event is 6 or more hours in the future.
> 
> **Solution:**
> I removed setting "All Day" events to defaulted UTC timezone. This change would make the defaulted time zone match the user's/calendar's configured time zone, resulting in default hour's time to be as close to the user's current hour.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by knchau** [comment]
Hi @rafaprax,

Do you have an ETA of when you can review this PR?

Thank you!

**Comment by rafaprax** [comment]
Hey @knchau , I'm going to take a look at this on next Thuersday, since today and tomorrow I'm on PTO.

Thx

**Comment by rafaprax** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
Hey @knchau, I'm still able to reproduce the issue with your fix. Can you please check the fix and resend? 

Thx

**Comment by knchau** [comment]
Commit remains unchanged, the steps to reproduce are updated: https://github.com/rafaprax/liferay-portal/pull/995

**Pull request closed without merging**
