### PR TITLE
LPS-78974 SF

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/652. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/7899c74c1539~1...7899c74c1539) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jpince** [comment]
cc/ @pedroqueiroz

**Comment by pedroqueiroz** [comment]
That was on me, @jpince, sorry. There was a time PortalSmoke used to be in the middle of flaky tests, so I learned to ignored them. Won't happen again. :)

**Comment by jpince** [comment]
Sounds good, thanks!

**Pull request closed without merging**
