### PR TITLE
LPS-80833 Check if the responseData is not null to not publish invalid form

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Hey girls @marcelabc @alinedoleron I think we can fix that just thown an exception at [this](https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-web/src/main/java/com/liferay/dynamic/data/mapping/form/web/internal/portlet/action/PublishFormInstanceMVCResourceCommand.java#L74) line instead. Can you please apply this approach?

Thx

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/58709. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/643. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/b7f3e751e88a~1...b7f3e751e88a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/58829. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/b7f3e751e88a~1...b7f3e751e88a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/58836. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
