### PR TITLE
LPS-79497 Define evaluating to true to be part of the evaluation cycle

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
@pedroqueiroz @matuzalemsteles I found a regression here. The data binding in the form builder between sidebar and the field no longer works. I've tested without this change and everything works perfectly. see problem below

bfp8rvfvg0

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
Sent to BChan at https://github.com/brianchandotcom/liferay-portal/pull/58200.

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/inacionery/liferay-portal/pull/554.

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/inacionery/liferay-portal/pull/556.

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/inacionery/liferay-portal/pull/557.

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/inacionery/liferay-portal/pull/558.

**Pull request closed without merging**
