### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests tomcat 9

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test

**Comment by marcelabc** [comment]
@vicnate5 Can we cover this with poshi or manual test?

**Comment by vicnate5** [comment]
@marcelabc https://issues.liferay.com/browse/LRQA-40212

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/502. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/913bf962cd89~1...913bf962cd89) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
