### PR TITLE
LPS-77693 SF

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
@vicnate5 Can you check if these errors are related to this pr? Thx

**Comment by vicnate5** [comment]
There is a regression here.
**Cannot access System Settings > DDM > Forms or Dynamic Data Mapping Service**
```
ERROR [http-nio-8080-exec-7][render_portlet_jsp:131] null
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at com.liferay.dynamic.data.mapping.type.text.internal.TextDDMFormFieldTemplateContextContributor.getValue(TextDDMFormFieldTemplateContextContributor.java:188)
	at com.liferay.dynamic.data.mapping.type.text.internal.TextDDMFormFieldTemplateContextContributor.getParameters(TextDDMFormFieldTemplateContextContributor.java:74)
	at com.liferay.dynamic.data.mapping.form.renderer.internal.DDMFormFieldTemplateContextFactory.setDDMFormFieldTemplateContextContributedParameters(DDMFormFieldTemplateContextFactory.java:350)
	at com.liferay.dynamic.data.mapping.form.renderer.internal.DDMFormFieldTemplateContextFactory.createDDMFormFieldTemplateContext(DDMFormFieldTemplateContextFactory.java:196)
	at com.liferay.dynamic.data.mapping.form.renderer.internal.DDMFormFieldTemplateContextFactory.createDDMFormFieldTemplateContexts(DDMFormFieldTemplateContextFactory.java:220)
	at com.liferay.dynamic.data.mapping.form.renderer.internal.DDMFormFieldTemplateContextFactory.create(DDMFormFieldTemplateContextFactory.java:75)
	at com.liferay.dynamic.data.mapping.form.renderer.internal.DDMFormPagesTemplateContextFactory.createFieldTemplateContext(DDMFormPagesTemplateContextFactory.java:168)
	at com.liferay.dynamic.data.mapping.form.renderer.internal.DDMFormPagesTemplateContextFactory.createFieldsTemplateContext(DDMFormPagesTemplateContextFactory.java:152)
	at com.liferay.dynamic.data.mapping.form.renderer.internal.DDMFormPagesTemplateContextFactory.createColumnTemplateContext(DDMFormPagesTemplateContextFactory.java:138)
	at com.liferay.dynamic.data.mapping.form.renderer.internal.DDMFormPagesTemplateContextFactory.createColumnsTemplateContext(DDMFormPagesTemplateContextFactory.java:125)
	at com.liferay.dynamic.data.mapping.form.renderer.internal.DDMFormPagesTemplateContextFactory.createRowTemplateContext(DDMFormPagesTemplateContextFactory.java:248)
	at com.liferay.dynamic.data.mapping.form.renderer.internal.DDMFormPagesTemplateContextFactory.createRowsTemplateContext(DDMFormPagesTemplateContextFactory.java:235)
	at com.liferay.dynamic.data.mapping.form.renderer.internal.DDMFormPagesTemplateContextFactory.createPageTemplateContext(DDMFormPagesTemplateContextFactory.java:213)
	at com.liferay.dynamic.data.mapping.form.renderer.internal.DDMFormPagesTemplateContextFactory.createPagesTemplateContext(DDMFormPagesTemplateContextFactory.java:180)
	at com.liferay.dynamic.data.mapping.form.renderer.internal.DDMFormPagesTemplateContextFactory.create(DDMFormPagesTemplateContextFactory.java:88)
	at com.liferay.dynamic.data.mapping.form.renderer.internal.DDMFormTemplateContextFactoryImpl.getPages(DDMFormTemplateContextFactoryImpl.java:231)
	at com.liferay.dynamic.data.mapping.form.renderer.internal.DDMFormTemplateContextFactoryImpl.doCreate(DDMFormTemplateContextFactoryImpl.java:148)
	at com.liferay.dynamic.data.mapping.form.renderer.internal.DDMFormTemplateContextFactoryImpl.create(DDMFormTemplateContextFactoryImpl.java:86)
	at com.liferay.dynamic.data.mapping.form.renderer.internal.DDMFormRendererImpl.populateCommonContext(DDMFormRendererImpl.java:185)
	at com.liferay.dynamic.data.mapping.form.renderer.internal.DDMFormRendererImpl.doRender(DDMFormRendererImpl.java:132)
```
cannotaccesssystemsetting

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/57695. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/464e863ddc96~1...464e863ddc96) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
