### PR TITLE
LPS-76721 Ignore test while LPS-77168 is not fixed

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test:sf

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62113. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/ae675eb10afc~1...ae675eb10afc) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
