### PR TITLE
LPS-112909 - Fix affected poshi tests

### PR DESCRIPTION
**Pull request by rodrigocunhaa**

### CODE REVIEW

**Comment by rodrigocunhaa** [comment]
ci:test:sf

**Comment by rodrigocunhaa** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:forward

**Pull request closed without merging**
