### PR TITLE
LPS-69023 Use latest

### PR DESCRIPTION
**Pull request by marcellustavares**
cc @leoadb

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:reopen

**Comment by marcellustavares** [comment]
Sorry @rafaprax, could you help me to fix this test?

**Comment by marcellustavares** [comment]
ci:restest

**Comment by marcellustavares** [comment]
ci:stop

**Comment by marcellustavares** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/46632. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
