### PR TITLE
LPS-80000 | Disable Autosave

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Rebased and sent to BChan at https://github.com/brianchandotcom/liferay-portal/pull/59890.

**Pull request closed without merging**
