### PR TITLE
LPS-82132 | Master

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test:sf

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/754. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/d44aa4a01227~1...d44aa4a01227) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
