### PR TITLE
LPS-76445 Copy translations and remove old language key

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
Hey @vicnate5, The markup changes on this pr affected the `LocalFile.ApplicationdisplaytemplatesUsecase#ADTTagsNavigationPortlet` test, Could you please take a look on that? 

Thx

**Comment by vicnate5** [comment]
Forwarded with Test fixes
https://github.com/rafaprax/liferay-portal/pull/481

**Comment by vicnate5** [comment]
ci:close

**Comment by rafaprax** [comment]
Thx @vicnate5

**Pull request closed without merging**
