### PR TITLE
LPS-74323 Semantic Versioning

### PR DESCRIPTION
**Pull request by pedroqueiroz94**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:reopen

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51806. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/27de9cbf785a~3...27de9cbf785a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
