### PR TITLE
LPS-86936 Use article default locale, or site default locale if new article, as the default display language.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
Fix to this issue was sent to BChan at https://github.com/brianchandotcom/liferay-portal/pull/64996

**Pull request closed without merging**
