### PR TITLE
LPS-97748 Add only active users

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @rafaprax 

Could you please review this pull request?
I added a check for active user so only such users can be selected for workflow task assignment.

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
Dear @rafaprax 

I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by rafaprax** [comment]
Hey @IstvanD , I'm currently on vacation. Please forward this to @inacionery. Thx

**Comment by IstvanD** [comment]
Hi @rafaprax 

I'm sorry for bothering you on your vacation.

I'll send the pull to @inacionery

Best regards,
István

**Comment by rafaprax** [comment]
No problem @IstvanD

**Pull request closed without merging**
