### PR TITLE
LPS-77063 Auto SF

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test

**Comment by alinedoleron** [comment]
ci:close

**Comment by alinedoleron** [comment]
ci:open

**Comment by alinedoleron** [comment]
ci:test

**Comment by timpak** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:stop

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by pedroqueiroz** [comment]
ci:retest

**Comment by pedroqueiroz** [comment]
ci:retest

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55765. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
