### PR TITLE
LPS-79109 Auto SF

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rodrigopaulino** [comment]
Hey, @pedroqueiroz.

I believe the "Actual Result" reported in the ticket is still happening. Tried a couple of times cleaning the browser cache and making sure that I was using a clean bundle compiled from this pull.
Also, in the browser console I noticed this error:

screen shot 2018-05-31 at 17 00 57

Could you help me double check this?
Thanks a lot.

**Comment by pedroqueiroz** [comment]
hey, @rodrigopaulino , if you add new translations only to the default language, this error should not happen. Although we are blocking editions in non-default languages, I'm adding an extra commit to make the code more robust.

Thanks!

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rodrigopaulino** [comment]
@pedroqueiroz, since your last commit does not have relation with the new purpose of this bug and, as you said, we will not be editing options at translated languages, I'm moving forward the entire pull __except__ your last commit. Also, your that commit introduces a new __unexpected__ behavior:
Adding a new option at translated language with value "op_br", after saving the Form, the value of this new option at default language goes to "opbr". I think this happens because you chose to pass the `option.value`, instead of `option.label`. See https://github.com/rafaprax/liferay-portal/pull/670/commits/3c4692503a84cfd0b2f96c0745b26b3adae826ae#diff-243d89458dbd339980734de6fbe2f5ceR119

**Comment by rodrigopaulino** [comment]
Sent to BChan. See https://github.com/brianchandotcom/liferay-portal/pull/59696

**Pull request closed without merging**
