### PR TITLE
LPS-79747 Open side bar when the page is empty

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
Hi @vicnate5, we have a new behavior on forms creation. Every time we have that blue space with "Drag from sidebar and drop here", which `id` is `#lfr-initial-col-message` the sidebar will open by default.
Therefore, when we create a new form or add a new page, initially the sidebar will open.

**Comment by vicnate5** [comment]
@alinedoleron This is an awesome improvement! Will fix the tests

**Comment by vicnate5** [comment]
Resent with test updates
https://github.com/rafaprax/liferay-portal/pull/530

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
