### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test

**Comment by alinedoleron** [comment]
ci:test

**Comment by alinedoleron** [comment]
ci:test

**Comment by alinedoleron** [comment]
Hi @rafaprax, I don't know what is "modules-compile-jdk8" faiIure, neither Rodrigo. But the others I believe they're not related to my fix.

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56998. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
