### PR TITLE
LPS-59291

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/32471

Thx

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/32488. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/9aaafdd~1...9aaafdd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/32490. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/b4c135f~1...b4c135f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
