### PR TITLE
[TECHNICAL-SUPPORT] LPS-80356

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @SpencerWoo

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by SpencerWoo** [comment]
Hi @rafaprax any update on this one?  thanks

**Comment by rafaprax** [comment]
Hey @SpencerWoo, I'm going to take a look on that tomorrow. Thx

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/SpencerWoo/liferay-portal/pull/17. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/34f8cb333a0b~1...34f8cb333a0b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/58498. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/6878c311666c~1...6878c311666c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
