### PR TITLE
LPS-78779 Update operands visibility

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
Hi @ vicnate5! Please, could you take a look at this poshi LocalFile.FormRules # ConfigureUserBelongsToRule? I don't know what's happening. I've tested locally and the button is being abled. :/

**Comment by vicnate5** [comment]
@alinedoleron I can reproduce this problem manually.

Steps
1. Create 2 text fields
1. Go to Rules
1. Add a rule
If User Belongs to Administrator
Show field2

Result: Save is disabled

screenshot 2018-05-30 09 58 20

**Comment by alinedoleron** [comment]
Thank you, @vicnate5! I must have done something wrong while testing. I fixed it now.

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
The latest poshi test failures are not related to the fix.

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/672. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/c1e5668c4d78~1...c1e5668c4d78) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
