### PR TITLE
LPS-102251 This is not necessary: it is stored in WorkflowTaskSearch object and saveOrderBy parameter is never used

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79303. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
merged at https://github.com/brianchandotcom/liferay-portal/pull/79303

**Pull request closed without merging**
