### PR TITLE
LPS-79447 Update locator for argument select field

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rodrigopaulino** [comment]
Review done and additional commits were sent to https://github.com/rafaprax/liferay-portal/pull/620.

**Pull request closed without merging**
