### PR TITLE
LPS-77347 | Forms Perfomance Bug

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@pedroqueiroz Issue 2 and 3 from https://github.com/rafaprax/liferay-portal/pull/551#issuecomment-385482191 are still present here.

**Comment by pedroqueiroz** [comment]
@vicnate5  I could not reproduce locally :/ Does it happen in any browser?

**Comment by vicnate5** [comment]
@pedroqueiroz I can reproduce on multiple browsers.

chromefieldlabel

chromeemailnotifications

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
Closing this, since @brunobasto is taking a look on it and will send another PR.

**Pull request closed without merging**
