### PR TITLE
LPS-78779 Simplify

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Hey @vicnate5 I think there is no unique failures here but can you double check?

Thx

**Comment by vicnate5** [comment]
@rafaprax it is good.

Failures are known test issues or due to https://issues.liferay.com/browse/LPS-81357

**Comment by rafaprax** [comment]
Thx @vicnate5

**Comment by rafaprax** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/59471. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/dc7b101187c2~3...dc7b101187c2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
