### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:stop

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
Hey @leoadb,

After the tests run, Could you please review there changes?

**Comment by rodrigo-e-c-souza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
@rodrigo-e-c-souza will take a look at the unique PR failures. :)

**Comment by rodrigo-e-c-souza** [comment]
Hi @linolaoj,

there is still a bug in Multiple Selection, it is not possible to delete an option unless you delete its content first.

**Comment by linolaoj** [comment]
Hi @rodrigo-e-c-souza , thank you for catching this. 
@rafaprax, sent a new pr https://github.com/rafaprax/liferay-portal/pull/321
Thanks!

**Pull request closed without merging**
