### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
Hey @vicnate5, we have changed the way Autocomplete feature is enabled, so we need to update the poshi tests.

Also, LocalFile.Forms#AddFormWithSpanishAsDefaultPortalLanguage is failing due to Modern Site Building changes.

Can you, please, take a look a that? Thanks!

**Comment by vicnate5** [comment]
Forwarded https://github.com/rafaprax/liferay-portal/pull/375

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
