### PR TITLE
LPS-75462 | master

### PR DESCRIPTION
**Pull request by vicnate5**
@pedroqueiroz @linolaoj

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
hi @vicnate5 , Forms#ViewFormWithMultipleSelectionFieldAsASwitcherAndHideLabel is failing due to the new macro. :/ Can you please take a look at that? Thanks!!

**Comment by vicnate5** [comment]
@pedroqueiroz I caused a test regression, will fix.

**Comment by vicnate5** [comment]
Updated.

The other failures will be fixed by https://github.com/rafaprax/liferay-portal/pull/382

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
@pedroqueiroz Looks good now. Failure are unrelated issues.

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Resent at https://github.com/rafaprax/liferay-portal/pull/386.

**Pull request closed without merging**
