### PR TITLE
[TS] LPS-98525

### PR DESCRIPTION
**Pull request by brianikim**
Hello @rafaprax,

I have resent from: https://github.com/natocesarrego/liferay-portal/pull/155 as requested by @natocesarrego

As established in PTR-980 and PTR-1043, performance in Calendar needs to be improved. I have addressed the deletion and re-creation of calendarBookings for updateCalendarBooking, specifically for the updates of childCalendarBookings. I am sending you this PR directly as you have prior knowledge of this issue stemming from the two PTRs.

Please let me know if you have any questions. Thanks.

Sincerely,
Brian Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by brianikim** [comment]
Hello @rafaprax ,

The test failures look good.

Please let me know if you have any questions. Thanks.

Sincerely,
Brian Kim

**Comment by rafaprax** [comment]
Hey @brianikim , nice. I'm not be able to review this pr now and I gonna take a look on that next week.

Thx

**Comment by brianikim** [comment]
Hello @rafaprax ,

That is fine. I do appreciate the quick update on the ETA. Have a great weekend :)

Sincerely,
Brian Kim

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:help

**Comment by rafaprax** [comment]
ci:test:upgrade

**Comment by rafaprax** [comment]
ci:test:staging

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/960. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/c84f4a1b9c3a~1...c84f4a1b9c3a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
