### PR TITLE
LPS-79424 Add integration test

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:stop

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/638. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/1893745e26c0~1...1893745e26c0) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/marcellustavares/liferay-portal/pull/1903. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/1893745e26c0~1...1893745e26c0) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
