### PR TITLE
LPS-80930 Inject services via constructor instead use *ServiceUtil

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
@linolaoj is going to apply a fix on top of this PR, so this should be on hold

**Comment by linolaoj** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by linolaoj** [comment]
Hi @pedroqueiroz, I could not reproduce LPS-81269 on this branch.

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Sent to BChan at https://github.com/brianchandotcom/liferay-portal/pull/58931.

**Pull request closed without merging**
