### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:retest

**Comment by leoadb** [comment]
@alinedoleron SF errors e some Poshi tests are broken. Can you please resend?

**Comment by leoadb** [comment]
ci:close

**Comment by alinedoleron** [comment]
sent to https://github.com/rafaprax/liferay-portal/pull/326

**Pull request closed without merging**
