### PR TITLE
LPS-79494 Create fields according to dataType

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
hey @vicnate5, are there any unique failures here? I think the validation one :(

**Comment by vicnate5** [comment]
@pedroqueiroz You are correct, the validation one. Just needed a test update.

Resent: https://github.com/rafaprax/liferay-portal/pull/583

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
