### PR TITLE
[TECHNICAL-SUPPORT] LPS-78433

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @MichaelPrigge

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
LGTM!

**Comment by pedroqueiroz** [comment]
@rafaprax , can we cover this with unit test?

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Hey @jonathanmccann @MichaelPrigge , I have changed some things in this PR and resent to https://github.com/rafaprax/liferay-portal/pull/400. 

Can you please take a look? Thanks!

**Comment by MichaelPrigge** [comment]
Hi @pedroqueiroz,

Thanks for your work on this issue. I believe those changes make sense here and I'm hoping to take a closer look at them tomorrow.

Thanks!

**Pull request closed without merging**
