### PR TITLE
LPS-77605 get ddmFormField for record version

### PR DESCRIPTION
**Pull request by linolaoj**
cc/ @pedroqueiroz94

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
Thanks, @linolaoj !

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
Sent to BChan at https://github.com/brianchandotcom/liferay-portal/pull/55226.

**Comment by pedroqueiroz94** [comment]
hey @linolaoj , can you see BChan's comment and rename the variables in the PR? Sorry about that. :(

**Comment by rafaprax** [comment]
@linolaoj @pedroqueiroz94  Hey guys, I can do the changes BChan requested. Thx

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55244. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/d736d6d5b17b~2...d736d6d5b17b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
