### PR TITLE
LPS-80851 keeping current page after submit error

### PR DESCRIPTION
**Pull request by linolaoj**
cc: @andreldm

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Hey @linolaoj there is a related error here. `LocalFile.Forms_SubmitFormContainingCaptchaAndViewTextFieldValue` cause: `JAVA_SCRIPT_ERROR: TypeError: currentPageInput is null`

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
LGTM

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
sent to https://github.com/brianchandotcom/liferay-portal/pull/58549

**Pull request closed without merging**
