### PR TITLE
LPS-82408 Add unit test

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test:sf

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/60683. [See changes here.](https://github.com/rafaprax/liferay-portal/compare/e3939bd5449c~2...e3939bd5449c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
