### PR TITLE
LRQA-37132 Ignoring the test for further analysis

### PR DESCRIPTION
**Pull request by rodrigo-e-c-souza**

### CODE REVIEW

**Comment by rodrigo-e-c-souza** [comment]
ci:retests

**Comment by rodrigo-e-c-souza** [comment]
ci:reopen

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
Resent at https://github.com/rafaprax/liferay-portal/pull/318.

**Pull request closed without merging**
