### PR TITLE
LPS-77677 | LPS-79109

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
@vicnate5, can you take a look at this one? :)

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@pedroqueiroz Unique failure here is that a form will not save if I change the default Portal language.

**Comment by pedroqueiroz** [comment]
will take a look on this, @vicnate5 , thanks!

**Comment by pedroqueiroz** [comment]
Resent LPS-77677 https://github.com/rafaprax/liferay-portal/pull/669.

**Pull request closed without merging**
